### ISSUE TITLE
The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths

### ISSUE THREAD

**Issue by Strubbl** [pixelfed/pixelfed#1084]
I got the following error:

```
[2019-03-26 22:53:57] production.ERROR: The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. {"exception":"[object] (RuntimeException(code: 0): The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. at /var/www/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:43)
[stacktrace]
#0 /var/www/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(28): Illuminate\\Encryption\\Encrypter->__construct('frapatilj12Seyk...', 'AES-256-CBC')                                                                        
#1 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(791): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(Object(Illuminate\\Foundation\\Application), Array)                                   
#2 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(671): Illuminate\\Container\\Container->build(Object(Closure))                                                                                                                   
#3 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(619): Illuminate\\Container\\Container->resolve('encrypter', Array)                                                                                                              
#4 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(757): Illuminate\\Container\\Container->make('encrypter', Array)                                                                                                              
#5 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(929): Illuminate\\Foundation\\Application->make('encrypter')                                                                                                                     
#6 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(857): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))                                                                                                
#7 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(822): Illuminate\\Container\\Container->resolveDependencies(Array)                                                                                                               
#8 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(671): Illuminate\\Container\\Container->build('App\\\\Http\\\\Middle...')                                                                                                        
#9 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(619): Illuminate\\Container\\Container->resolve('App\\\\Http\\\\Middle...', Array)                                                                                               
#10 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(757): Illuminate\\Container\\Container->make('App\\\\Http\\\\Middle...', Array)                                                                                              
#11 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(152): Illuminate\\Foundation\\Application->make('App\\\\Http\\\\Middle...')                                                                                                       
#12 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))                                                                            
#13 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))                                                                            
#14 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))                                                                                                                          
#15 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))                                                        
#16 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))                                                                   
#17 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))                                                                                                
#18 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))                                                                                               
#19 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))                                                              
#20 /var/www/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))                                                                                               
#21 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))                                                                                  
#22 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))                                                                            
#23 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))                                                  
#24 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))                                                     
#25 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))                                                                            
#26 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))                                                  
#27 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))                                                     
#28 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))                                                                            
#29 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))                                                   
#30 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))                                                      
#31 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))                                                                            
#32 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))                                            
#33 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))                                               
#34 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))                                                                            
#35 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))                                                                            
#36 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))                                                                                                                  
#37 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))                                                                      
#38 /var/www/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#39 {main}
"}
[2019-03-26 22:53:57] production.ERROR: The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. {"exception":"[object] (RuntimeException(code: 0): The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. at /var/www/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:43)
[stacktrace]
#0 /var/www/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(28): Illuminate\\Encryption\\Encrypter->__construct('frapatilj12Seyk...', 'AES-256-CBC')                                                                        
#1 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(791): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(Object(Illuminate\\Foundation\\Application), Array)                                   
#2 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(671): Illuminate\\Container\\Container->build(Object(Closure))                                                                                                                   
#3 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(619): Illuminate\\Container\\Container->resolve('encrypter', Array)                                                                                                              
#4 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(757): Illuminate\\Container\\Container->make('encrypter', Array)                                                                                                              
#5 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(929): Illuminate\\Foundation\\Application->make('encrypter')                                                                                                                     
#6 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(857): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))                                                                                                
#7 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(822): Illuminate\\Container\\Container->resolveDependencies(Array)                                                                                                               
#8 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(671): Illuminate\\Container\\Container->build('App\\\\Http\\\\Middle...')                                                                                                        
#9 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(619): Illuminate\\Container\\Container->resolve('App\\\\Http\\\\Middle...', Array)                                                                                               
#10 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(757): Illuminate\\Container\\Container->make('App\\\\Http\\\\Middle...', Array)                                                                                              
#11 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(215): Illuminate\\Foundation\\Application->make('App\\\\Http\\\\Middle...')                                                                                                  
#12 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(189): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))                                       
#13 /var/www/public/index.php(58): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))                                                                                                    
#14 {main}
"}
```

Solution for me was to set the APP_KEY to the length of 32 chars. Mine was only 31 long. O.o

This issue is only to document the error and a solution.

**Comment by albjeremias** [comment]
@Strubbl can u please explain how you solve this? I stumbled in the same error..
