### ISSUE TITLE
The InboxWorker job fails in 0.9.0

### ISSUE THREAD

**Issue by carbontwelve** [pixelfed/pixelfed#1156]
> Pixelfed: 0.9.0
> PHP 7.3.4

I am unsure if this is because I upgraded from 0.8; but all `InboxWorker` jobs now fail.

```
Symfony\Component\HttpKernel\Exception\HttpException in /srv/www/federated.photos/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:985
--
Stack trace:
#0 /srv/www/federated.photos/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(46): Illuminate\Foundation\Application->abort(422, '', Array)
#1 /srv/www/federated.photos/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(66): abort(422, '', Array)
#2 /srv/www/federated.photos/httpdocs/app/Util/ActivityPub/Helpers.php(194): abort_if(true, 422)
#3 /srv/www/federated.photos/httpdocs/app/Util/ActivityPub/Helpers.php(203): App\Util\ActivityPub\Helpers::fetchFromUrl('https://magnifi...')
#4 /srv/www/federated.photos/httpdocs/app/Util/ActivityPub/Helpers.php(391): App\Util\ActivityPub\Helpers::fetchProfileFromUrl('https://magnifi...')
#5 /srv/www/federated.photos/httpdocs/app/Util/ActivityPub/Inbox.php(105): App\Util\ActivityPub\Helpers::profileFirstOrNew('https://magnifi...')
#6 /srv/www/federated.photos/httpdocs/app/Util/ActivityPub/Inbox.php(280): App\Util\ActivityPub\Inbox->actorFirstOrCreate('https://magnifi...')
#7 /srv/www/federated.photos/httpdocs/app/Util/ActivityPub/Inbox.php(69): App\Util\ActivityPub\Inbox->handleLikeActivity()
#8 /srv/www/federated.photos/httpdocs/app/Util/ActivityPub/Inbox.php(40): App\Util\ActivityPub\Inbox->handleVerb()
#9 /srv/www/federated.photos/httpdocs/app/Jobs/InboxPipeline/InboxWorker.php(40): App\Util\ActivityPub\Inbox->handle()
#10 [internal function]: App\Jobs\InboxPipeline\InboxWorker->handle()
#11 /srv/www/federated.photos/httpdocs/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#12 /srv/www/federated.photos/httpdocs/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#13 /srv/www/federated.photos/httpdocs/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#14 /srv/www/federated.photos/httpdocs/vendor/laravel/framework/src/Illuminate/Container/Container.php(580): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#15 /srv/www/federated.photos/httpdocs/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#16 /srv/www/federated.photos/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\InboxPipeline\InboxWorker))
#17 /srv/www/federated.photos/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\InboxPipeline\InboxWorker))
#18 /srv/www/federated.photos/httpdocs/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 /srv/www/federated.photos/httpdocs/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\InboxPipeline\InboxWorker), false)
#20 /srv/www/federated.photos/httpdocs/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(86): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#21 /srv/www/federated.photos/httpdocs/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(327): Illuminate\Queue\Jobs\Job->fire()
#22 /srv/www/federated.photos/httpdocs/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(277): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#23 /srv/www/federated.photos/httpdocs/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#24 /srv/www/federated.photos/httpdocs/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\Queue\Worker->daemon('redis', 'default', Object(Illuminate\Queue\WorkerOptions))
#25 /srv/www/federated.photos/httpdocs/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(86): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'default')
#26 /srv/www/federated.photos/httpdocs/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\Queue\Console\WorkCommand->handle()
#27 [internal function]: Laravel\Horizon\Console\WorkCommand->handle()
#28 /srv/www/federated.photos/httpdocs/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#29 /srv/www/federated.photos/httpdocs/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#30 /srv/www/federated.photos/httpdocs/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#31 /srv/www/federated.photos/httpdocs/vendor/laravel/framework/src/Illuminate/Container/Container.php(580): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#32 /srv/www/federated.photos/httpdocs/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#33 /srv/www/federated.photos/httpdocs/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#34 /srv/www/federated.photos/httpdocs/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#35 /srv/www/federated.photos/httpdocs/vendor/symfony/console/Application.php(908): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /srv/www/federated.photos/httpdocs/vendor/symfony/console/Application.php(269): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /srv/www/federated.photos/httpdocs/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 /srv/www/federated.photos/httpdocs/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#39 /srv/www/federated.photos/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#40 /srv/www/federated.photos/httpdocs/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#41 {main}


```

**Comment by dansup** [comment]
@carbontwelve This is fixed in the latest commits, don't forget to run the [post deployment](https://docs.pixelfed.org/master/deployment.html#post-deployment-commands) commands after updating!

**Comment by carbontwelve** [comment]
~~@dansup I'm currently on tagged 0.9.0 do I just need to checkout the `dev` branch?~~

Awesome, it works 👍

**Comment by maxheadroom** [comment]
I've just seen this very same error on my newly install Pixelfed 0.10.9 instance 

```

Symfony\Component\Debug\Exception\FatalThrowableError:  syntax error, unexpected ')' in  /home/pixelfeed/pixelfed/app/Util/ActivityPub/Inbox.php:303
--
Stack trace:
#0 /home/pixelfeed/pixelfed/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/pixelfeed...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Util\\Activi...')

```
