### ISSUE TITLE
Alerts - Spinning wheel in 0.9.4

### ISSUE THREAD

**Issue by olliware** [pixelfed/pixelfed#1348]
Hey everyone,

just set up a new Pixelfed-instance by cloning the Git-repository. Everything went well except the spinning wheel driving me crazy straight under "Alerts". Is this already a known issue?

![Bildschirmfoto 2019-06-04 um 17 12 59](https://user-images.githubusercontent.com/42076599/58891136-47695500-86ec-11e9-8e9d-f3bdbb89bca5.jpg)

Thanks in advance,

Oliver

**Comment by dansup** [comment]
@olliware This is likely a deployment error. If you have no notifications, a message/icon will appear. Can you paste the dev tools console errors?

**Comment by okpierre** [comment]
@olliware @dansup 

Here's what I'm seeing on my end with 0.9.4 - hope that helps

![pixelfed-094-alert-notification](https://user-images.githubusercontent.com/1679025/58921841-77255680-8706-11e9-9afa-44caef71d589.png)

**Comment by olliware** [comment]
> @olliware @dansup
> 
> Here's what I'm seeing on my end with 0.9.4 - hope that helps
> 
> ![pixelfed-094-alert-notification](https://user-images.githubusercontent.com/1679025/58921841-77255680-8706-11e9-9afa-44caef71d589.png)

I think this is the way it should look like ;) !

**Comment by olliware** [comment]
> @olliware This is likely a deployment error. If you have no notifications, a message/icon will appear. Can you paste the dev tools console errors?

Sorry for the dumb question - how do I accomplish this? Or are you referring to the dev tools of the browser (neither works with latest Firefox and Safari BTW)?

**Comment by jk-na** [comment]
I'm having the same issue, other than the Stop! spiel in console view, I'm getting the following:

`Error: request failed with status code 500 - app.js:1:11910`

**Comment by gegeweb** [comment]
Same error for me.

**Comment by gegeweb** [comment]
If that help I've this in laravel.log

```
[2019-06-14 10:28:40] production.ERROR: Non-static method Redis::zRangeByScore() cannot be called statically {"userId":1,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Non-static method Redis::zRangeByScore() cannot be called statically at /usr/local/www/pixelfed/app/Services/NotificationService.php:24)
[stacktrace]
#0 /usr/local/www/pixelfed/app/Http/Controllers/Api/BaseApiController.php(72): App\\Services\\NotificationService::get(1, 0, 10)
#1 [internal function]: App\\Http\\Controllers\\Api\\BaseApiController->notifications(Object(Illuminate\\Http\\Request))
#2 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#3 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('notifications', Array)
#4 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\ApiController), 'notifications')
#5 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#6 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#7 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#8 /usr/local/www/pixelfed/app/Http/Middleware/Localization.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#9 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\Localization->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#10 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#11 /usr/local/www/pixelfed/app/Http/Middleware/TwoFactorAuth.php(33): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#12 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\TwoFactorAuth->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /usr/local/www/pixelfed/app/Http/Middleware/EmailVerificationCheck.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\EmailVerificationCheck->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#39 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#40 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#41 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#42 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#43 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#44 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#45 /usr/local/www/pixelfed/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#49 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#52 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#55 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#58 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#61 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#62 /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#63 /usr/local/www/pixelfed/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#64 {main}
"} 
```

**Comment by dansup** [comment]
@gegeweb The issue is you have the ```redisPHP``` PECL extension installed and it is conflicting with the ```predis``` library the framework uses. 

You can either uninstall that extension, or update the ```database.php``` config as mentioned [here](https://laravel.com/docs/5.8/redis#phpredis)

**Comment by olliware** [comment]
Closed without further help regarding the problem why this issue has been opened. Okay...

**Comment by okpierre** [comment]
@olliware issue that many are reporting was also closed - odd because we're not sure if there was a fix or not

**composer dependencies are not up to date**

https://github.com/pixelfed/pixelfed/issues/1393

**Comment by olliware** [comment]
OK, thanks clarifying 👍🏻 !

**Comment by dansup** [comment]
@olliware This was closed because it's not a bug in pixelfed, but a deployment error.

**Comment by jk-na** [comment]
@dansup apologies for commenting on this closed issue, but I still have the same problem, I don't have `redisPHP` installed nor was it referenced in the `database.php`.

I've updated the `config/database.php` to use `predis` (as opposed to `phpredis`) and configured as per [](https://laravel.com/docs/5.8/redis) and have cleared cache, route, restarted php-fpm and nginx.. still getting exactly the same error in the laravel.log.

I've had my pixelfed instance since December last year and have updated to 0.9.4 in the same tried and tested manner as I have previous releases\commits - artisan self-diagnosis sees no issues.

System stack is: pixelfed 0.9.4, postgres 10.7, php 7.2.17, laravel 5.8.23

Are there any additional steps you could recommend to resolve this? Should I open another issue for the same problem?

**Comment by olliware** [comment]
What worked for me was leaving the database.php in its original state and I simply removed the php-redis module on my machine. Going after the documentation didn't change anything so for now I just deinstalled php-redis and am fine with Pixelfed. Try this - just to focus on reproducing this error. Fortunately I don't have any application needing php-redis at the moment but who knows?

**Comment by jk-na** [comment]
I tried removing the php-redis module and it stopped supervisor from being able to restart horizon - caused fatal errors - possibly as my DB & Redis are hosted on another server?

**Comment by gegeweb** [comment]
@jk-na @dansup the same here.

**Comment by gegeweb** [comment]
Okay, it's working now. as mentioned by @olliware : database.php in its original state, removed the php pecl redis module. Restarting php-fpm and workers.
But with phpredis (and the pecl module installed) in database.php, that doesn't works.

**Comment by jk-na** [comment]
OK, working for me now too.. I did everything except restart horizon and ran `php artisan horizon:assets && php artisan horizon:install` and supervisor can restart the workers, thanks @olliware & @gegeweb

**Comment by olliware** [comment]
> OK, working for me now too.. I did everything except restart horizon and ran `php artisan horizon:assets && php artisan horizon:install` and supervisor can restart the workers, thanks @olliware & @gegeweb

Great to read that it worked for you, too - nice community work here 👍 !

**Comment by carbontwelve** [comment]
@dansup the cause of this issue is because the `Redis` facade in php clashes with the `Redis` class name for the PECL extension. 

A working solution is to reference the full namespace for the laravel facade `use Illuminate\Support\Facades\Redis;`

While you have closed this issue citing "deployment error" it could be argued that it's an incompatibility brought about by the way PIxelfed utilises Laravel and as it is something that can easily be accommodated I'd say its a bug.
