### ISSUE TITLE
Changing my profile name raises a "not null violation" exception

### ISSUE THREAD

**Issue by kstrauser** [pixelfed/pixelfed#1372]
Whenever I change my profile name, the resulting notification (I _think_ this is sending an update message to my federated followers?) results in a not-null constraint violation in the `notifications` table:

```
[2019-06-08 19:40:24] production.ERROR: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "profile_id" violates not-null constraint
DETAIL:  Failing row contains (15, null, null, null, null, null, null, 2019-06-08 19:40:24, 2019-06-08 19:40:24, null, null, null). (SQL: insert into "notifications" ("updated_at", "created_at") values (2019-06-08 19:40:24, 2019-06-08 19:40:24) returning "id") {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23502)
: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"profile_id\" violates not-null constraint
DETAIL:  Failing row contains (15, null, null, null, null, null, null, 2019-06-08 19:40:24, 2019-06-08 19:40:24, null, null, null). (SQL: insert into \"notifications\" (\"updated_at\", \"created_at\") values (2019-06-08 19:40:24, 2019-06-08 19:40:24) returning \"id\") at /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Data
base/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"profile_id\" violates not-null constraint
DETAIL:  Failing row contains (15, null, null, null, null, null, null, 2019-06-08 19:40:24, 2019-06-08 19:40:24, null, null, null). at /var/lib/pixelfed/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119, PDOException(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"profile_id\" vio
lates not-null constraint
DETAIL:  Failing row contains (15, null, null, null, null, null, null, 2019-06-08 19:40:24, 2019-06-08 19:40:24, null, null, null). at /var/lib/pixelfed/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)
[stacktrace]
#0 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('insert into \"no...', Array, Object(Closure))
#1 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('insert into \"no...', Array, Object(Closure))
#2 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php(304): Illuminate\\Database\\Connection->select('insert into \"no...', Array, false)
#3 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/PostgresProcessor.php(20): Illuminate\\Database\\Connection->selectFromWriteConnection('insert into \"no...', Array)
#4 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2657): Illuminate\\Database\\Query\\Processors\\PostgresProcessor->processInsertGetId(Object(Illuminate\\Database\\Query\\Builder), 'insert into \"no...', Array, 'id')
#5 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1347): Illuminate\\Database\\Query\\Builder->insertGetId(Array, 'id')
#6 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(835): Illuminate\\Database\\Eloquent\\Builder->__call('insertGetId', Array)
#7 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(800): Illuminate\\Database\\Eloquent\\Model->insertAndSetId(Object(Illuminate\\Database\\Eloquent\\Builder), Array)
#8 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(663): Illuminate\\Database\\Eloquent\\Model->performInsert(Object(Illuminate\\Database\\Eloquent\\Builder))
#9 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(420): Illuminate\\Database\\Eloquent\\Model->save()
#10 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1123): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\{closure}(Object(App\\Notification))
#11 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(421): tap(Object(App\\Notification), Object(Closure))
#12 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->firstOrCreate(Array)
#13 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1614): Illuminate\\Database\\Eloquent\\Model->forwardCallTo(Object(Illuminate\\Database\\Eloquent\\Builder), 'firstOrCreate', Array)
#14 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1626): Illuminate\\Database\\Eloquent\\Model->__call('firstOrCreate', Array)
#15 /var/lib/pixelfed/app/Util/ActivityPub/Inbox.php(230): Illuminate\\Database\\Eloquent\\Model::__callStatic('firstOrCreate', Array)
#16 /var/lib/pixelfed/app/Util/ActivityPub/Inbox.php(55): App\\Util\\ActivityPub\\Inbox->handleAnnounceActivity()
#17 /var/lib/pixelfed/app/Util/ActivityPub/Inbox.php(39): App\\Util\\ActivityPub\\Inbox->handleVerb()
#18 /var/lib/pixelfed/app/Jobs/InboxPipeline/InboxWorker.php(40): App\\Util\\ActivityPub\\Inbox->handle()
#19 [internal function]: App\\Jobs\\InboxPipeline\\InboxWorker->handle()
#20 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#21 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#22 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#23 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#24 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#25 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\InboxPipeline\\InboxWorker))
#26 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\InboxPipeline\\InboxWorker))
#27 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#28 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\InboxPipeline\\InboxWorker), false)
#29 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(86): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\RedisJob), Array)
#30 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(327): Illuminate\\Queue\\Jobs\\Job->fire()
#31 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(277): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#32 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#33 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\\Queue\\Worker->daemon('redis', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#34 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(86): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'default')
#35 /var/lib/pixelfed/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\\Queue\\Console\\WorkCommand->handle()
#36 [internal function]: Laravel\\Horizon\\Console\\WorkCommand->handle()
#37 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#38 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#39 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#40 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#41 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#42 /var/lib/pixelfed/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#43 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#44 /var/lib/pixelfed/vendor/symfony/console/Application.php(908): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#45 /var/lib/pixelfed/vendor/symfony/console/Application.php(269): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#46 /var/lib/pixelfed/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#47 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#48 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#49 /var/lib/pixelfed/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#50 {main}
"}
```

**Comment by dansup** [comment]
@kstrauser I cannot reproduce this. Please make sure you are running the latest commits.
