### ISSUE TITLE
Not Receiving Email Confirmations

### ISSUE THREAD

**Issue by nickian** [pixelfed/pixelfed#1400]
I definitely have the correct SMTP settings in my .env, but I'm not receiving confirmation emails. What is the best way to diagnose this? Apache error log is empty.

I have `APP_DEBUG` set to `true`.

I have run:

```
php artisan config:cache
php artisan route:cache
```

And `php artisan self-diagnosis` shows this:

```
|-------------------------------------
| Common Checks
|-------------------------------------
Running check 1/11: App key is set...  ✔
Running check 2/11: The correct PHP version is installed...  ✔
Running check 3/11: The database can be accessed...  ✔
Running check 4/11: All directories have the correct permissions...  ✔
Running check 5/11: The environment file exists...  ✔
Running check 6/11: The example environment variables are set...  ✔
Running check 7/11: Required locales are installed...  ✘
Running check 8/11: Maintenance mode is not enabled...  ✔
Running check 9/11: The migrations are up to date...  ✔
Running check 10/11: The required PHP extensions are installed...  ✔
Running check 11/11: The storage directory is linked...  ✔

|-------------------------------------
| Environment Specific Checks (production)
|-------------------------------------
Running check 1/5: Composer dependencies (without dev) are up to date...  ✘
Running check 2/5: Configuration is cached...  ✔
Running check 3/5: Debug mode is not enabled...  ✘
Running check 4/5: Unwanted PHP extensions are disabled...  ✔
Running check 5/5: Routes are cached...  ✔

The following checks failed:
The following locales are missing:
en_US

Your composer dependencies are not up to date. Call "composer install" to update them. Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 0 installs, 0 updates, 32 removals
  - Uninstalling webmozart/assert (1.4.0)
  - Uninstalling theseer/tokenizer (1.1.2)
  - Uninstalling sebastian/version (2.0.1)
  - Uninstalling sebastian/resource-operations (2.0.1)
  - Uninstalling sebastian/recursion-context (3.0.0)
  - Uninstalling sebastian/object-reflector (1.1.1)
  - Uninstalling sebastian/object-enumerator (3.0.3)
  - Uninstalling sebastian/global-state (2.0.0)
  - Uninstalling sebastian/exporter (3.1.0)
  - Uninstalling sebastian/environment (4.2.2)
  - Uninstalling sebastian/diff (3.0.2)
  - Uninstalling sebastian/comparator (3.0.2)
  - Uninstalling sebastian/code-unit-reverse-lookup (1.0.1)
  - Uninstalling phpunit/phpunit (7.5.9)
  - Uninstalling phpunit/php-token-stream (3.0.1)
  - Uninstalling phpunit/php-timer (2.1.1)
  - Uninstalling phpunit/php-text-template (1.2.1)
  - Uninstalling phpunit/php-file-iterator (2.0.2)
  - Uninstalling phpunit/php-code-coverage (6.1.4)
  - Uninstalling phpspec/prophecy (1.8.0)
  - Uninstalling phpdocumentor/type-resolver (0.4.0)
  - Uninstalling phpdocumentor/reflection-docblock (4.3.1)
  - Uninstalling phpdocumentor/reflection-common (1.0.1)
  - Uninstalling phar-io/version (2.0.1)
  - Uninstalling phar-io/manifest (1.0.3)
  - Uninstalling nunomaduro/collision (v2.1.1)
  - Uninstalling myclabs/deep-copy (1.9.1)
  - Uninstalling mockery/mockery (1.2.2)
  - Uninstalling hamcrest/hamcrest-php (v2.0.0)
  - Uninstalling fzaninotto/faker (v1.8.0)
  - Uninstalling filp/whoops (2.3.1)
  - Uninstalling doctrine/instantiator (1.2.0)

You should not use debug mode in production. Set "APP_DEBUG" in the .env file to "false".
```

Do emails have anything to do with Redis config?

**Comment by trwnh** [comment]
I think you should check your SMTP settings in your .env file.

**Comment by nickian** [comment]
No, I think it has to do with the job queue or something. I set up a test.php file with SwiftMailer with the exact same SMTP settings and I get the emails just fine.

There seems to be a lot of instructions missing from the install documentation. Nothing about Laravel Horizon is mentioned either. Is that required? I feel like my Redis is not configured correctly, but I don't know how to diagnose. Thumnail previews are also not being generated reliably.

**Comment by nickian** [comment]
I'm seeing these errors in laravel.log:

```
[2019-06-15 16:02:43] production.ERROR: Non-static method Redis::zRangeByScore() cannot be called statically {"userId":1,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Non-static method Redis::zRangeByScore() cannot be called statically at /www/app/Services/NotificationService.php:24)
[stacktrace]
#0 /www/app/Http/Controllers/Api/BaseApiController.php(72): App\\Services\\NotificationService::get(1, 0, 10)
#1 [internal function]: App\\Http\\Controllers\\Api\\BaseApiController->notifications(Object(Illuminate\\Http\\Request))
#2 /www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#3 /www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('notifications', Array)
#4 /www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\ApiController), 'notifications')
#5 /www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#6 /www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#7 /www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#8 /www/app/Http/Middleware/Localization.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#9 /www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\Localization->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#10 /www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#11 /www/app/Http/Middleware/TwoFactorAuth.php(33): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#12 /www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\TwoFactorAuth->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 /www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /www/app/Http/Middleware/EmailVerificationCheck.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 /www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\EmailVerificationCheck->handle(Object(Illuminate\\Http\\Request), Object(Closure))
...
```

**Comment by dansup** [comment]
@nickian To fix the issue, you can uninstall phpredis or update the database config file to load the proper driver as described here: 

https://laravel.com/docs/5.8/redis#phpredis

**Comment by nickian** [comment]
I removed phpredis. That didn't help. I reinstalled it and changed the database.php driver to use it, still no emails. Horizon show up normal in admin and thumbnails are working fine, however.

**Comment by nickian** [comment]
Figured it out. I had `MAIL_DRIVER=log` in the .env. Had to change it to `MAIL_DRIVER=smtp`. :persevere:
