### ISSUE TITLE
Compose Post Beta - not federating

### ISSUE THREAD

**Issue by jk-na** [pixelfed/pixelfed#1672]
Hi,

I posted two images earlier one via Beta and one via the normal process.

Beta: https://px.nipponalba.scot/p/jk/75861141275938816
Normal: https://px.nipponalba.scot/p/jk/75862479963557888

The Beta post didn't federate nor does it seem to display the location anywhere.  I did see a fediverse post about making sure to update to PHP 7.3.9 and I'm on 7.3.4 so possible that covers the location bit.

Stack: Pixelfed 0.10.2, Postgres 10.10, PHP 7.3.4-2, Laravel 5.8.35

The following is the failed job output from horizon:

```
ErrorException:  Trying to get property 'name' of non-object in  /usr/share/nginx/html/pixelfed/app/Transformer/ActivityPub/Verb/CreateNote.php:80
--
Stack trace:
#0   /usr/share/nginx/html/pixelfed/app/Transformer/ActivityPub/Verb/CreateNote.php(80):  Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8,  'Trying to get p...', '/usr/share/ngin...', 80, Array)
#1   /usr/share/nginx/html/pixelfed/vendor/pixelfed/fractal/src/Scope.php(407):   App\Transformer\ActivityPub\Verb\CreateNote->transform(Object(App\Status))
#2   /usr/share/nginx/html/pixelfed/vendor/pixelfed/fractal/src/Scope.php(346):   League\Fractal\Scope->fireTransformer(Object(App\Transformer\ActivityPub\Verb\CreateNote),  Object(App\Status))
#3   /usr/share/nginx/html/pixelfed/vendor/pixelfed/fractal/src/Scope.php(235):  League\Fractal\Scope->executeResourceTransformers()
#4 /usr/share/nginx/html/pixelfed/app/Jobs/StatusPipeline/StatusActivityPubDeliver.php(69): League\Fractal\Scope->toArray()
#5 [internal function]: App\Jobs\StatusPipeline\StatusActivityPubDeliver->handle()
#6   /usr/share/nginx/html/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32):  call_user_func_array(Array, Array)
#7   /usr/share/nginx/html/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90):  Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#8   /usr/share/nginx/html/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34):   Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application),  Array, Object(Closure))
#9   /usr/share/nginx/html/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(576):   Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application),  Array, Array, NULL)
#10   /usr/share/nginx/html/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94):  Illuminate\Container\Container->call(Array)
#11   /usr/share/nginx/html/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128):   Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\StatusPipeline\StatusActivityPubDeliver))
#12   /usr/share/nginx/html/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104):   Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\StatusPipeline\StatusActivityPubDeliver))
#13   /usr/share/nginx/html/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98):  Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14   /usr/share/nginx/html/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49):   Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\StatusPipeline\StatusActivityPubDeliver),  false)
#15   /usr/share/nginx/html/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(88):   Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob),  Array)
#16   /usr/share/nginx/html/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(337):  Illuminate\Queue\Jobs\Job->fire()
#17   /usr/share/nginx/html/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(283):  Illuminate\Queue\Worker->process('redis',  Object(Illuminate\Queue\Jobs\RedisJob),  Object(Illuminate\Queue\WorkerOptions))
#18   /usr/share/nginx/html/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118):   Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob),  'redis', Object(Illuminate\Queue\WorkerOptions))
#19   /usr/share/nginx/html/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102):  Illuminate\Queue\Worker->daemon('redis', 'default',  Object(Illuminate\Queue\WorkerOptions))
#20   /usr/share/nginx/html/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(86):  Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'default')
#21   /usr/share/nginx/html/pixelfed/vendor/laravel/horizon/src/Console/WorkCommand.php(46):  Illuminate\Queue\Console\WorkCommand->handle()
#22 [internal function]: Laravel\Horizon\Console\WorkCommand->handle()
#23   /usr/share/nginx/html/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32):  call_user_func_array(Array, Array)
#24   /usr/share/nginx/html/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90):  Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#25   /usr/share/nginx/html/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34):   Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application),  Array, Object(Closure))
#26   /usr/share/nginx/html/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(576):   Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application),  Array, Array, NULL)
#27   /usr/share/nginx/html/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(183):  Illuminate\Container\Container->call(Array)
#28   /usr/share/nginx/html/pixelfed/vendor/symfony/console/Command/Command.php(255):   Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput),  Object(Illuminate\Console\OutputStyle))
#29   /usr/share/nginx/html/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(170):   Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput),  Object(Illuminate\Console\OutputStyle))
#30   /usr/share/nginx/html/pixelfed/vendor/symfony/console/Application.php(915):   Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput),  Object(Symfony\Component\Console\Output\ConsoleOutput))
#31   /usr/share/nginx/html/pixelfed/vendor/symfony/console/Application.php(272):   Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand),  Object(Symfony\Component\Console\Input\ArgvInput),  Object(Symfony\Component\Console\Output\ConsoleOutput))
#32   /usr/share/nginx/html/pixelfed/vendor/symfony/console/Application.php(148):   Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput),  Object(Symfony\Component\Console\Output\ConsoleOutput))
#33   /usr/share/nginx/html/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Application.php(90):   Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput),  Object(Symfony\Component\Console\Output\ConsoleOutput))
#34   /usr/share/nginx/html/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(133):   Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput),  Object(Symfony\Component\Console\Output\ConsoleOutput))
#35  /usr/share/nginx/html/pixelfed/artisan(37):  Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput),  Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 {main}

```

Data:

```
{
status: {
class: "App\Status",
id: 75861141275938820,
relations: [
"profile"
],
connection: "pgsql"
},
deleteWhenMissingModels: true,
job: null,
connection: null,
queue: null,
chainConnection: null,
chainQueue: null,
delay: null,
chained: [
]
} 

```

**Comment by dansup** [comment]
@jk-na Did you run ```php artisan import:cities``` ?

**Comment by jk-na** [comment]
> @jk-na Did you run `php artisan import:cities` ?

I did, yes and the location search etc. worked, the location just appears not to have been published when the post was finished.

I've just run it again followed by config:cache, route:cache and both location and federation worked.

I wonder if the failure yesterday was caused by exploring the advanced settings before I posted.

I've have just noticed though that when I use the crop function the next screen applies a filter, even though 'no filter' is selected.

**Comment by jk-na** [comment]
I'll play about with the filter issue on different browsers and devices as it seems to be ok from my phone.. but firefox is applying a filter despite no filter being selected.  anyway, if the issue persists I'll open a separate ticket, this issues seems to be resolved after the refresh.
