### ISSUE TITLE
Can't follow from an other instance with Postgresql

### ISSUE THREAD

**Issue by raphgilles** [pixelfed/pixelfed#2030]
Hello,

The users of an instance who works with Postgresql can't be followed from an external instance.
For example if you want to follow https://pixelfed.fr/raph on Mastodon it will still pending.

I think this will need a fix to accept all pending invitations.

All is ok with an instance with mysql.

In the laravel log I have :

> [2020-02-16 17:03:39] Production.ERROR: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "profile_id" violates not-null constraint
DETAIL:  Failing row contains (21285651, null, null, null, null, null, null, 2020-02-16 17:03:39, 2020-02-16 17:03:39, null, null, null). (SQL: insert into "notifications" ("updated_at", "created_at") values (2020-02-16 17:03:39, 2020-02-16 17:03:39) returning "id") {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"profile_id\" violates not-null constraint
DETAIL:  Failing row contains (21285651, null, null, null, null, null, null, 2020-02-16 17:03:39, 2020-02-16 17:03:39, null, null, null). (SQL: insert into \"notifications\" (\"updated_at\", \"created_at\") values (2020-02-16 17:03:39, 2020-02-16 17:03:39) returning \"id\") at /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669)
[stacktrace]
#0 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\\Database\\Connection->runQueryCallback()
#1 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php(338): Illuminate\\Database\\Connection->run()
#2 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php(309): Illuminate\\Database\\Connection->select()
#3 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/PostgresProcessor.php(20): Illuminate\\Database\\Connection->selectFromWriteConnection()
#4 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2670): Illuminate\\Database\\Query\\Processors\\PostgresProcessor->processInsertGetId()
#5 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1350): Illuminate\\Database\\Query\\Builder->insertGetId()
#6 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(839): Illuminate\\Database\\Eloquent\\Builder->__call()
#7 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(804): Illuminate\\Database\\Eloquent\\Model->insertAndSetId()
#8 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(667): Illuminate\\Database\\Eloquent\\Model->performInsert()
#9 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(422): Illuminate\\Database\\Eloquent\\Model->save()
#10 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Support/helpers.php(422): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\{closure}()
#11 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(423): tap()
#12 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->firstOrCreate()
#13 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1618): Illuminate\\Database\\Eloquent\\Model->forwardCallTo()
#14 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1630): Illuminate\\Database\\Eloquent\\Model->__call()
#15 /home/pixelfed/app/Util/ActivityPub/Inbox.php(189): Illuminate\\Database\\Eloquent\\Model::__callStatic()
#16 /home/pixelfed/app/Util/ActivityPub/Inbox.php(54): App\\Util\\ActivityPub\\Inbox->handleFollowActivity()
#17 /home/pixelfed/app/Util/ActivityPub/Inbox.php(42): App\\Util\\ActivityPub\\Inbox->handleVerb()
#18 /home/pixelfed/app/Jobs/InboxPipeline/InboxWorker.php(43): App\\Util\\ActivityPub\\Inbox->handle()
#19 [internal function]: App\\Jobs\\InboxPipeline\\InboxWorker->handle()
#20 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#21 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#22 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure()
#23 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod()
#24 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call()
#25 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call()
#26 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#27 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then()
#29 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\\Bus\\Dispatcher->dispatchNow()
#30 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#31 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\\Pipeline\\Pipeline->then()
#33 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#34 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(88): Illuminate\\Queue\\CallQueuedHandler->call()
#35 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(354): Illuminate\\Queue\\Jobs\\Job->fire()
#36 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(300): Illuminate\\Queue\\Worker->process()
#37 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(134): Illuminate\\Queue\\Worker->runJob()
#38 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon()
#39 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#40 /home/pixelfed/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\\Queue\\Console\\WorkCommand->handle()
#41 [internal function]: Laravel\\Horizon\\Console\\WorkCommand->handle()
#42 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#43 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#44 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure()
#45 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod()
#46 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call()
#47 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(202): Illuminate\\Container\\Container->call()
#48 /home/pixelfed/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#49 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(189): Symfony\\Component\\Console\\Command\\Command->run()
#50 /home/pixelfed/vendor/symfony/console/Application.php(1011): Illuminate\\Console\\Command->run()
#51 /home/pixelfed/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand()
#52 /home/pixelfed/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#53 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#54 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run()
#55 /home/pixelfed/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#56 {main}

[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"profile_id\" violates not-null constraint
DETAIL:  Failing row contains (21285651, null, null, null, null, null, null, 2020-02-16 17:03:39, 2020-02-16 17:03:39, null, null, null). at /home/pixelfed/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123)
[stacktrace]
#0 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php(335): Doctrine\\DBAL\\Driver\\PDOStatement->execute()
#1 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php(662): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#2 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\\Database\\Connection->runQueryCallback()
#3 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php(338): Illuminate\\Database\\Connection->run()
#4 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php(309): Illuminate\\Database\\Connection->select()
#5 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/PostgresProcessor.php(20): Illuminate\\Database\\Connection->selectFromWriteConnection()
#6 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2670): Illuminate\\Database\\Query\\Processors\\PostgresProcessor->processInsertGetId()
#7 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1350): Illuminate\\Database\\Query\\Builder->insertGetId()
#8 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(839): Illuminate\\Database\\Eloquent\\Builder->__call()
#9 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(804): Illuminate\\Database\\Eloquent\\Model->insertAndSetId()
#10 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(667): Illuminate\\Database\\Eloquent\\Model->performInsert()
#11 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(422): Illuminate\\Database\\Eloquent\\Model->save()
#12 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Support/helpers.php(422): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\{closure}()
#13 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(423): tap()
#14 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->firstOrCreate()
#15 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1618): Illuminate\\Database\\Eloquent\\Model->forwardCallTo()
#16 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1630): Illuminate\\Database\\Eloquent\\Model->__call()
#17 /home/pixelfed/app/Util/ActivityPub/Inbox.php(189): Illuminate\\Database\\Eloquent\\Model::__callStatic()
#18 /home/pixelfed/app/Util/ActivityPub/Inbox.php(54): App\\Util\\ActivityPub\\Inbox->handleFollowActivity()
#19 /home/pixelfed/app/Util/ActivityPub/Inbox.php(42): App\\Util\\ActivityPub\\Inbox->handleVerb()
#20 /home/pixelfed/app/Jobs/InboxPipeline/InboxWorker.php(43): App\\Util\\ActivityPub\\Inbox->handle()
#21 [internal function]: App\\Jobs\\InboxPipeline\\InboxWorker->handle()
#22 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#23 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#24 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure()
#25 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod()
#26 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call()
#27 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call()
#28 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#29 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then()
#31 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\\Bus\\Dispatcher->dispatchNow()
#32 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#33 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\\Pipeline\\Pipeline->then()
#35 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#36 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(88): Illuminate\\Queue\\CallQueuedHandler->call()
#37 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(354): Illuminate\\Queue\\Jobs\\Job->fire()
#38 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(300): Illuminate\\Queue\\Worker->process()
#39 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(134): Illuminate\\Queue\\Worker->runJob()
#40 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon()
#41 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#42 /home/pixelfed/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\\Queue\\Console\\WorkCommand->handle()
#43 [internal function]: Laravel\\Horizon\\Console\\WorkCommand->handle()
#44 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#45 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#46 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure()
#47 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod()
#48 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call()
#49 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(202): Illuminate\\Container\\Container->call()
#50 /home/pixelfed/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#51 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(189): Symfony\\Component\\Console\\Command\\Command->run()
#52 /home/pixelfed/vendor/symfony/console/Application.php(1011): Illuminate\\Console\\Command->run()
#53 /home/pixelfed/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand()
#54 /home/pixelfed/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#55 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#56 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run()
#57 /home/pixelfed/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#58 {main}

[previous exception] [object] (PDOException(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"profile_id\" violates not-null constraint
DETAIL:  Failing row contains (21285651, null, null, null, null, null, null, 2020-02-16 17:03:39, 2020-02-16 17:03:39, null, null, null). at /home/pixelfed/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121)
[stacktrace]
#0 /home/pixelfed/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(121): PDOStatement->execute()
#1 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php(335): Doctrine\\DBAL\\Driver\\PDOStatement->execute()
#2 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php(662): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#3 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\\Database\\Connection->runQueryCallback()
#4 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php(338): Illuminate\\Database\\Connection->run()
#5 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php(309): Illuminate\\Database\\Connection->select()
#6 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/PostgresProcessor.php(20): Illuminate\\Database\\Connection->selectFromWriteConnection()
#7 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2670): Illuminate\\Database\\Query\\Processors\\PostgresProcessor->processInsertGetId()
#8 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1350): Illuminate\\Database\\Query\\Builder->insertGetId()
#9 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(839): Illuminate\\Database\\Eloquent\\Builder->__call()
#10 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(804): Illuminate\\Database\\Eloquent\\Model->insertAndSetId()
#11 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(667): Illuminate\\Database\\Eloquent\\Model->performInsert()
#12 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(422): Illuminate\\Database\\Eloquent\\Model->save()
#13 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Support/helpers.php(422): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\{closure}()
#14 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(423): tap()
#15 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->firstOrCreate()
#16 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1618): Illuminate\\Database\\Eloquent\\Model->forwardCallTo()
#17 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1630): Illuminate\\Database\\Eloquent\\Model->__call()
#18 /home/pixelfed/app/Util/ActivityPub/Inbox.php(189): Illuminate\\Database\\Eloquent\\Model::__callStatic()
#19 /home/pixelfed/app/Util/ActivityPub/Inbox.php(54): App\\Util\\ActivityPub\\Inbox->handleFollowActivity()
#20 /home/pixelfed/app/Util/ActivityPub/Inbox.php(42): App\\Util\\ActivityPub\\Inbox->handleVerb()
#21 /home/pixelfed/app/Jobs/InboxPipeline/InboxWorker.php(43): App\\Util\\ActivityPub\\Inbox->handle()
#22 [internal function]: App\\Jobs\\InboxPipeline\\InboxWorker->handle()
#23 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#24 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#25 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure()
#26 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod()
#27 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call()
#28 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call()
#29 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#30 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then()
#32 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\\Bus\\Dispatcher->dispatchNow()
#33 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#34 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\\Pipeline\\Pipeline->then()
#36 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#37 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(88): Illuminate\\Queue\\CallQueuedHandler->call()
#38 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(354): Illuminate\\Queue\\Jobs\\Job->fire()
#39 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(300): Illuminate\\Queue\\Worker->process()
#40 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(134): Illuminate\\Queue\\Worker->runJob()
#41 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon()
#42 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#43 /home/pixelfed/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\\Queue\\Console\\WorkCommand->handle()
#44 [internal function]: Laravel\\Horizon\\Console\\WorkCommand->handle()
#45 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#46 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#47 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure()
#48 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod()
#49 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call()
#50 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(202): Illuminate\\Container\\Container->call()
#51 /home/pixelfed/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#52 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(189): Symfony\\Component\\Console\\Command\\Command->run()
#53 /home/pixelfed/vendor/symfony/console/Application.php(1011): Illuminate\\Console\\Command->run()
#54 /home/pixelfed/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand()
#55 /home/pixelfed/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#56 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#57 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run()
#58 /home/pixelfed/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#59 {main}
"}

Thank you !

**Comment by dansup** [comment]
@raphgilles Just tested this on Mastodon, I was able to successfully follow your account. The postgres fixes I shipped yesterday might have fixed this issue. Please advise if this is still an issue!

**Comment by raphgilles** [comment]
@dansup Please return or refresh on Mastodon the page of my profile. I just tried a new, and it's always in pending.

**Comment by raphgilles** [comment]
This log is from after the fix of yesterday.

**Comment by dansup** [comment]
@raphgilles Yes, I can confirm the following:

- I follow your account from Mastodon
- The request reaches your instance and I'm added as a follower (your follower count went up by 1)
- The Accept follow object sent from your instance to Mastodon is either not fired or fails due to a postgres/laravel CI bug I assume

Are you able to join the ```#pixelfed-dev``` channel on freenode so we can discuss this further?

**Comment by cliqsocial** [comment]
@raphgilles Glad you are reporting this issue. We reported it https://github.com/pixelfed/pixelfed/issues/1947 and it was closed and marked as `wont' fix`
