### ISSUE TITLE
 Value for URI.HostBlacklist is of invalid type, should be list invoked on line 23 in file /pxlfd/vendor/stevebauman/purify/src/Purify.php

### ISSUE THREAD

**Issue by Dryusdan** [pixelfed/pixelfed#2312]
Hi

This issue is duplicate as #1812 but the problem still here and I not found how to resolve it.

All of my queue failed, and when I push again on task, I have this log : 

```
[2020-07-08 10:09:59] production.ERROR: Value for URI.HostBlacklist is of invalid type, should be list invoked on line 23 in file /var/www/dryc_art/www/vendor/stevebauman/purify/src/Purify.php {"exception":"[object] (ErrorException(code: 0): Value for URI.HostBlacklist is of invalid type, should be list invoked on line 23 in file /var/www/dryc_art/www/vendor/stevebauman/purify/src/Purify.php at /var/www/dryc_art/www/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php:901)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(512, 'Value for URI.H...', '/var/www/dryc_a...', 901, Array)
#1 /var/www/dryc_art/www/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php(901): trigger_error('Value for URI.H...', 512)
#2 /var/www/dryc_art/www/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php(352): HTMLPurifier_Config->triggerError('Value for URI.H...', 512)
APP_NAME="DryC-Art"
#3 /var/www/dryc_art/www/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php(687): HTMLPurifier_Config->set('URI.HostBlackli...', NULL)
#4 /var/www/dryc_art/www/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php(136): HTMLPurifier_Config->loadArray(Array)
#5 /var/www/dryc_art/www/vendor/stevebauman/purify/src/Purify.php(23): HTMLPurifier_Config::create(Array)
#6 /var/www/dryc_art/www/vendor/stevebauman/purify/src/PurifyServiceProvider.php(24): Stevebauman\\Purify\\Purify->__construct()
#7 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(799): Stevebauman\\Purify\\PurifyServiceProvider->Stevebauman\\Purify\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#8 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build(Object(Closure))
#9 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Container\\Container->resolve('purify', Array)
#10 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(769): Illuminate\\Container\\Container->make('purify', Array)
#11 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(1245): Illuminate\\Foundation\\Application->make('purify')
#12 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(198): Illuminate\\Container\\Container->offsetGet('purify')
#13 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(166): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance('purify')
#14 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(255): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()
#15 /var/www/dryc_art/www/app/Util/ActivityPub/Helpers.php(403): Illuminate\\Support\\Facades\\Facade::__callStatic('clean', Array)
#16 /var/www/dryc_art/www/app/Util/ActivityPub/Helpers.php(436): App\\Util\\ActivityPub\\Helpers::profileFirstOrNew('https://miaou.d...')
#17 /var/www/dryc_art/www/app/Util/ActivityPub/Inbox.php(107): App\\Util\\ActivityPub\\Helpers::profileFetch('https://miaou.d...')
#18 /var/www/dryc_art/www/app/Util/ActivityPub/Inbox.php(212): App\\Util\\ActivityPub\\Inbox->actorFirstOrCreate('https://miaou.d...')
#19 /var/www/dryc_art/www/app/Util/ActivityPub/Inbox.php(58): App\\Util\\ActivityPub\\Inbox->handleAnnounceActivity()
#20 /var/www/dryc_art/www/app/Util/ActivityPub/Inbox.php(42): App\\Util\\ActivityPub\\Inbox->handleVerb()
#21 /var/www/dryc_art/www/app/Jobs/InboxPipeline/InboxWorker.php(43): App\\Util\\ActivityPub\\Inbox->handle()
#22 [internal function]: App\\Jobs\\InboxPipeline\\InboxWorker->handle()
#23 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#24 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#25 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#26 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#27 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#28 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#29 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\InboxPipeline\\InboxWorker))
#30 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\InboxPipeline\\InboxWorker))
#31 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#32 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\InboxPipeline\\InboxWorker), false)
#33 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(App\\Jobs\\InboxPipeline\\InboxWorker))
#34 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\InboxPipeline\\InboxWorker))
#35 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#36 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(App\\Jobs\\InboxPipeline\\InboxWorker))
#37 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(88): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\RedisJob), Array)
#38 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(354): Illuminate\\Queue\\Jobs\\Job->fire()
#39 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(300): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#40 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(134): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#41 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon('redis', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#42 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'default')
#43 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#44 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#45 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#46 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#47 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#48 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#49 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(202): Illuminate\\Container\\Container->call(Array)
#50 /var/www/dryc_art/www/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#51 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(189): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#52 /var/www/dryc_art/www/vendor/symfony/console/Application.php(1011): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#53 /var/www/dryc_art/www/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#54 /var/www/dryc_art/www/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#55 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#56 /var/www/dryc_art/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#57 /var/www/dryc_art/www/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#58 {main}
```

I have these line of top on .env

```
ACTIVITY_PUB=true
AP_REMOTE_FOLLOW=true
AP_INBOX=true
PF_COSTAR_ENABLED=true

CS_BLOCKED_DOMAINS='gab.com,gab.ai,develop.gab.com,spinster.xyz'
CS_CW_DOMAINS='switter.at'
CS_UNLISTED_DOMAINS=''
CS_BLOCKED_KEYWORDiS=''
CS_CW_KEYWORDS=''
CS_UNLISTED_KEYWORDS=''
CS_BLOCKED_ACTOR=''
CS_CW_ACTOR=''
CS_UNLISTED_ACTOR=''
```

But when I set PF_COSTAR_ENABLED to false, the problem persist.

How I can solve it ? :)

**Comment by Dryusdan** [comment]
Found it...
It is because I use PostgreSQL instead of MySQL (dafuck O.O)

In doc ( https://docs.pixelfed.org/technical-documentation/env.html ) postgresql driver is supported...
