### ISSUE TITLE
InboxValidator has been attempted too many times or run too long

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2358]
```
App\Jobs\InboxPipeline\InboxValidator

Illuminate\Queue\MaxAttemptsExceededException: App\Jobs\InboxPipeline\InboxValidator has been attempted too many times or run too long. The job may have previously timed out. in /pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:649
Stack trace:
#0 /pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(163): Illuminate\Queue\Worker->maxAttemptsExceededException()
#1 /pixelfed/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(558): Illuminate\Queue\Worker->Illuminate\Queue\{closure}()
#2 [internal function]: GuzzleHttp\Handler\CurlFactory->GuzzleHttp\Handler\{closure}()
```

**Comment by dansup** [comment]
Fixed in #2665
