### ISSUE TITLE
ErrorException: Illegal string offset 'type' in .. pixelfed/app/Util/ActivityPub/Inbox.php:477 - postgresql

### ISSUE THREAD

**Issue by jk-na** [pixelfed/pixelfed#2525]
Seeing a massive amount of failed jobs in horizon with the following error:

`ErrorException: Illegal string offset 'type' in /usr/share/nginx/html/pixelfed/app/Util/ActivityPub/Inbox.php:477`

Full stacktrace:  https://pastebin.com/dqXNPaE8

![Screenshot_2020-12-22_13-30-55](https://user-images.githubusercontent.com/51400674/102893875-26955b80-445a-11eb-8819-012a2e550ae9.jpg)

Edit: replaced expired pastebin link with new one

**Comment by okpierre** [comment]
@jk-na besides failed jobs, do you also see pending jobs stuck?

**Comment by jk-na** [comment]
> @jk-na besides failed jobs, do you also see pending jobs stuck?

I don't have any pending jobs, but a variety of errors.  Some just duplicate keys etc.  another similar to above is:

`ErrorException: Undefined index: id in /usr/share/nginx/html/pixelfed/app/Util/ActivityPub/Helpers.php:307`

**Comment by SharkyRawr** [comment]
I got the same thing, fresh install, postgres database. It happened when I tried to follow a user that's not pixelfed but should be ActivityPub compatible.

```
ErrorException: Illegal string offset 'type' in /var/www/pixelfed.catgirl.biz/app/Util/ActivityPub/Inbox.php:477
--
Stack trace:
#0 /var/www/pixelfed.catgirl.biz/app/Util/ActivityPub/Inbox.php(477): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/pixelfed.catgirl.biz/app/Util/ActivityPub/Inbox.php(92): App\Util\ActivityPub\Inbox->handleDeleteActivity()
#2 /var/www/pixelfed.catgirl.biz/app/Util/ActivityPub/Inbox.php(49): App\Util\ActivityPub\Inbox->handleVerb()
#3 /var/www/pixelfed.catgirl.biz/app/Jobs/InboxPipeline/InboxWorker.php(60): App\Util\ActivityPub\Inbox->handle()
#4 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\InboxPipeline\InboxWorker->handle()
#5 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#7 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#8 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\Container\BoundMethod::call()
#9 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call()
#10 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#11 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#12 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#13 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(96): Illuminate\Bus\Dispatcher->dispatchNow()
#14 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#15 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#16 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(98): Illuminate\Pipeline\Pipeline->then()
#17 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(67): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#18 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#19 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(406): Illuminate\Queue\Jobs\Job->fire()
#20 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\Queue\Worker->process()
#21 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(158): Illuminate\Queue\Worker->runJob()
#22 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(116): Illuminate\Queue\Worker->daemon()
#23 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\Queue\Console\WorkCommand->runWorker()
#24 /var/www/pixelfed.catgirl.biz/vendor/laravel/horizon/src/Console/WorkCommand.php(50): Illuminate\Queue\Console\WorkCommand->handle()
#25 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle()
#26 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#27 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#28 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#29 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\Container\BoundMethod::call()
#30 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#31 /var/www/pixelfed.catgirl.biz/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute()
#32 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#33 /var/www/pixelfed.catgirl.biz/vendor/symfony/console/Application.php(971): Illuminate\Console\Command->run()
#34 /var/www/pixelfed.catgirl.biz/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#35 /var/www/pixelfed.catgirl.biz/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun()
#36 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run()
#37 /var/www/pixelfed.catgirl.biz/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#38 /var/www/pixelfed.catgirl.biz/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#39 {main}
```

**Comment by SharkyRawr** [comment]
This was fixed for me in `dev 91b7c043 Merge pull request #2569 from pixelfed/staging` 91b7c043be2d995e90afebb9ecb7f134996712d7

**Comment by jk-na** [comment]
Whilst the volume has thankfully reduced, I have two of these failures on my small, quiet instance in the past hour since updating to the latest commits.

**Comment by dansup** [comment]
@jk-na Working on resolving the remaining horizon job bugs, the latest commits fix the majority of them.

**Comment by jk-na** [comment]
I am still seeing these errors in the horizon logs, specifically for failed handling of delete activities from my pleroma account, it may not be unique to pleroma but I don't follow that many people and it seems to always be my account when I check the logs.

**Comment by jk-na** [comment]
Can this issue please be re-opened, I still haven't seen this resolved despite being on the latest commits, it currently makes up around 51% of failed jobs on my instance.
