### ISSUE TITLE
Video media isn't being uploaded to S3

### ISSUE THREAD

**Issue by cyberczar** [pixelfed/pixelfed#2652]
It doesn't look like the MediaStoragePipeline task (I'm assuming that's the task that moves the media eventually to the configured storage provider) is being called for any `video/mp4` media that is uploaded. Any videos uploaded are being stored in `/storage/m/_v2/...../` and is being served from the app server and not the CDN configured for the storage provider.

Same for the video thumbnails that are generated.

For non-video media uploaded, the pictures are being eventually uploaded and stored on the S3 storage provider.

Edit:

I don't know if this is related, but there are video thumbnail jobs that are failing so I'm not sure if this is related:

```
App\Jobs\VideoPipeline\VideoThumbnail
ID 2044aa98-d2a3-4343-bb14-dc9d61167164
Queue default
Attempts 4
Retries 0
Tags App\Media:133
Failed At 2021-02-13 13:15:24
````

```
Exception

Illuminate\Queue\MaxAttemptsExceededException: App\Jobs\VideoPipeline\VideoThumbnail has been attempted too many times or run too long. The job may have previously timed out. in /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:713
--
Stack trace:
#0 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(482): Illuminate\Queue\Worker->maxAttemptsExceededException(Object(Illuminate\Queue\Jobs\RedisJob))
#1 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(396): Illuminate\Queue\Worker->markJobAsFailedIfAlreadyExceedsMaxAttempts('redis', Object(Illuminate\Queue\Jobs\RedisJob), 3)
#2 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#3 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(158): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#4 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(116): Illuminate\Queue\Worker->daemon('redis', 'default', Object(Illuminate\Queue\WorkerOptions))
#5 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'default')
#6 /usr/share/webapps/pixelfed/vendor/laravel/horizon/src/Console/WorkCommand.php(50): Illuminate\Queue\Console\WorkCommand->handle()
#7 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle()
#8 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#9 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#10 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#11 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#12 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call(Array)
#13 /usr/share/webapps/pixelfed/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#14 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#15 /usr/share/webapps/pixelfed/vendor/symfony/console/Application.php(971): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /usr/share/webapps/pixelfed/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /usr/share/webapps/pixelfed/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /usr/share/webapps/pixelfed/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

```
Data
{
media: {
class: "App\Media",
id: 133,
relations: [
],
connection: "pgsql"
},
job: null,
connection: null,
queue: null,
chainConnection: null,
chainQueue: null,
chainCatchCallbacks: null,
delay: null,
afterCommit: null,
middleware: [
],
chained: [
]
}
```

**Comment by jimmybrancaccio** [comment]
I can confirm it looks like this is still partially happening on v0.11.1. Thumbnails for the video do appear to be getting generated but videos are not being uploaded to S3.

<img width="996" alt="Screen Shot 2021-10-29 at 7 58 58 PM" src="https://user-images.githubusercontent.com/405585/139514658-93fd7ce6-27b0-4cf3-a836-988293ef9b42.png">

<img width="1219" alt="Screen Shot 2021-10-29 at 8 00 27 PM" src="https://user-images.githubusercontent.com/405585/139514683-65c2f125-e616-4bca-8359-d21fb4eb3266.png">

I should note there is a pending VideoThumbnail job in the queue though (and it's still there 15 minutes later).

<img width="1127" alt="Screen Shot 2021-10-29 at 8 07 44 PM" src="https://user-images.githubusercontent.com/405585/139514938-632d96d3-362b-4f3f-b5cd-37b46a062663.png">

**Comment by jimmybrancaccio** [comment]
After some debugging last night the issue is partially with the PHP `memory_limit` but more specifically when the Blurhash functionality is called to create a blurhash from the video thumbnail. The thumbnails for videos don't end up getting resized like they do for images so they're quite large. In my testing I was using a 1080p video so the dimensions of the thumbnail were 1920x1080. Blurhash ended up needing more then 1GB of memory to process the thumbnail and create the blurhash.

In speaking with @dansup [on Discord](https://discord.com/channels/446875483016134658/804529634523873300/905560139577307137) he will be taking a look at this and I assume running the video thumbnails through a resize function so that the thumbnail is resized to something smaller and then the blurhash can be created. This will allow the pipeline to complete successfully (which includes uploading the thumbnail and video files to S3.
