### ISSUE TITLE
HttpSignature:40 Trying to get property 'private_key' of non-object

### ISSUE THREAD

**Issue by alarig** [pixelfed/pixelfed#2663]
Hi,

Each time I try to interact remotely (message, {un,}follow, etc. from mastodon, I have this traceback in the logs:

```
[2021-02-16 22:37:42] production.ERROR: Trying to get property 'private_key' of non-object {"exception":"[object] (ErrorException(code: 0): Trying to get property 'private_key' of non-object at /opt/pixelfed/pixelfed/app/Util/ActivityPub/HttpSignature.php:40)
[stacktrace]
#0 /opt/pixelfed/pixelfed/app/Util/ActivityPub/HttpSignature.php(40): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(420): App\\Util\\ActivityPub\\HttpSignature::App\\Util\\ActivityPub\\{closure}()
#2 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(406): Illuminate\\Cache\\Repository->rememberForever()
#3 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Cache\\CacheManager->__call()
#4 /opt/pixelfed/pixelfed/app/Util/ActivityPub/HttpSignature.php(41): Illuminate\\Support\\Facades\\Facade::__callStatic()
#5 /opt/pixelfed/pixelfed/app/Services/ActivityPubFetchService.php(20): App\\Util\\ActivityPub\\HttpSignature::instanceActorSign()
#6 /opt/pixelfed/pixelfed/app/Util/ActivityPub/Helpers.php(220): App\\Services\\ActivityPubFetchService::get()
#7 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(385): App\\Util\\ActivityPub\\Helpers::App\\Util\\ActivityPub\\{closure}()
#8 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(406): Illuminate\\Cache\\Repository->remember()
#9 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Cache\\CacheManager->__call()
#10 /opt/pixelfed/pixelfed/app/Util/ActivityPub/Helpers.php(227): Illuminate\\Support\\Facades\\Facade::__callStatic()
#11 /opt/pixelfed/pixelfed/app/Util/ActivityPub/Helpers.php(232): App\\Util\\ActivityPub\\Helpers::fetchFromUrl()
#12 /opt/pixelfed/pixelfed/app/Util/ActivityPub/Helpers.php(441): App\\Util\\ActivityPub\\Helpers::fetchProfileFromUrl()
#13 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(385): App\\Util\\ActivityPub\\Helpers::App\\Util\\ActivityPub\\{closure}()
#14 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(406): Illuminate\\Cache\\Repository->remember()
#15 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Cache\\CacheManager->__call()
#16 /opt/pixelfed/pixelfed/app/Util/ActivityPub/Helpers.php(497): Illuminate\\Support\\Facades\\Facade::__callStatic()
#17 /opt/pixelfed/pixelfed/app/Jobs/InboxPipeline/InboxValidator.php(170): App\\Util\\ActivityPub\\Helpers::profileFirstOrNew()
#18 /opt/pixelfed/pixelfed/app/Jobs/InboxPipeline/InboxValidator.php(120): App\\Jobs\\InboxPipeline\\InboxValidator->verifySignature()
#19 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\InboxPipeline\\InboxValidator->handle()
#20 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#21 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#22 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#23 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\\Container\\BoundMethod::call()
#24 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#25 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#26 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#28 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(118): Illuminate\\Bus\\Dispatcher->dispatchNow()
#29 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#30 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\\Pipeline\\Pipeline->then()
#32 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#33 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#34 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(406): Illuminate\\Queue\\Jobs\\Job->fire()
#35 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\\Queue\\Worker->process()
#36 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(158): Illuminate\\Queue\\Worker->runJob()
#37 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(116): Illuminate\\Queue\\Worker->daemon()
#38 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#39 /opt/pixelfed/pixelfed/vendor/laravel/horizon/src/Console/WorkCommand.php(50): Illuminate\\Queue\\Console\\WorkCommand->handle()
#40 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\WorkCommand->handle()
#41 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#42 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#43 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#44 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\\Container\\BoundMethod::call()
#45 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#46 /opt/pixelfed/pixelfed/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#47 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#48 /opt/pixelfed/pixelfed/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run()
#49 /opt/pixelfed/pixelfed/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand()
#50 /opt/pixelfed/pixelfed/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun()
#51 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#52 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#53 /opt/pixelfed/pixelfed/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#54 {main}
"} 
[2021-02-16 22:38:09] production.ERROR: Trying to get property 'private_key' of non-object {"exception":"[object] (ErrorException(code: 0): Trying to get property 'private_key' of non-object at /opt/pixelfed/pixelfed/app/Util/ActivityPub/HttpSignature.php:40)
[stacktrace]
#0 /opt/pixelfed/pixelfed/app/Util/ActivityPub/HttpSignature.php(40): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(420): App\\Util\\ActivityPub\\HttpSignature::App\\Util\\ActivityPub\\{closure}()
#2 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(406): Illuminate\\Cache\\Repository->rememberForever()
#3 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Cache\\CacheManager->__call()
#4 /opt/pixelfed/pixelfed/app/Util/ActivityPub/HttpSignature.php(41): Illuminate\\Support\\Facades\\Facade::__callStatic()
#5 /opt/pixelfed/pixelfed/app/Services/ActivityPubFetchService.php(20): App\\Util\\ActivityPub\\HttpSignature::instanceActorSign()
#6 /opt/pixelfed/pixelfed/app/Util/ActivityPub/Helpers.php(220): App\\Services\\ActivityPubFetchService::get()
#7 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(385): App\\Util\\ActivityPub\\Helpers::App\\Util\\ActivityPub\\{closure}()
#8 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(406): Illuminate\\Cache\\Repository->remember()
#9 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Cache\\CacheManager->__call()
#10 /opt/pixelfed/pixelfed/app/Util/ActivityPub/Helpers.php(227): Illuminate\\Support\\Facades\\Facade::__callStatic()
#11 /opt/pixelfed/pixelfed/app/Util/ActivityPub/Helpers.php(232): App\\Util\\ActivityPub\\Helpers::fetchFromUrl()
#12 /opt/pixelfed/pixelfed/app/Util/ActivityPub/Helpers.php(441): App\\Util\\ActivityPub\\Helpers::fetchProfileFromUrl()
#13 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(385): App\\Util\\ActivityPub\\Helpers::App\\Util\\ActivityPub\\{closure}()
#14 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(406): Illuminate\\Cache\\Repository->remember()
#15 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Cache\\CacheManager->__call()
#16 /opt/pixelfed/pixelfed/app/Util/ActivityPub/Helpers.php(497): Illuminate\\Support\\Facades\\Facade::__callStatic()
#17 /opt/pixelfed/pixelfed/app/Jobs/InboxPipeline/InboxWorker.php(158): App\\Util\\ActivityPub\\Helpers::profileFirstOrNew()
#18 /opt/pixelfed/pixelfed/app/Jobs/InboxPipeline/InboxWorker.php(111): App\\Jobs\\InboxPipeline\\InboxWorker->verifySignature()
#19 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\InboxPipeline\\InboxWorker->handle()
#20 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#21 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#22 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#23 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\\Container\\BoundMethod::call()
#24 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#25 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#26 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#28 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(118): Illuminate\\Bus\\Dispatcher->dispatchNow()
#29 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#30 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\\Pipeline\\Pipeline->then()
#32 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#33 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#34 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(406): Illuminate\\Queue\\Jobs\\Job->fire()
#35 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\\Queue\\Worker->process()
#36 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(158): Illuminate\\Queue\\Worker->runJob()
#37 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(116): Illuminate\\Queue\\Worker->daemon()
#38 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#39 /opt/pixelfed/pixelfed/vendor/laravel/horizon/src/Console/WorkCommand.php(50): Illuminate\\Queue\\Console\\WorkCommand->handle()
#40 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\WorkCommand->handle()
#41 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#42 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#43 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#44 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\\Container\\BoundMethod::call()
#45 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#46 /opt/pixelfed/pixelfed/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#47 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#48 /opt/pixelfed/pixelfed/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run()
#49 /opt/pixelfed/pixelfed/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand()
#50 /opt/pixelfed/pixelfed/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun()
#51 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#52 /opt/pixelfed/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#53 /opt/pixelfed/pixelfed/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#54 {main}
"} 
```

**Comment by dansup** [comment]
Run `php artisan instance:actor`
