### ISSUE TITLE
Something went wrong.  We cannot process your request at this time, please try again later. 

### ISSUE THREAD

**Issue by plant7403** [pixelfed/pixelfed#2831]
Hello, everyone 👋
Trying to run pixelfed with docker, image build was ok, but after running ```  docker-compose ``` on any page of pixelfed i see:
#### We cannot process your request at this time, please try again later. Go back to Pixelfed.

Same thing on the local port and the domain
Also in the log i have different exceptions with "No application encryption key has been specified":

```
[2021-06-30 10:03:28] production.ERROR: No application encryption key has been specified. {"exception":"[object] (Illuminate\\Encryption\\MissingAppKeyException(code: 0): No application encryption key has been specified. at /var/www/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:79)
[stacktrace]
#0 /var/www/vendor/laravel/framework/src/Illuminate/Support/helpers.php(263): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}()
#1 /var/www/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(81): tap()
#2 /var/www/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(60): Illuminate\\Encryption\\EncryptionServiceProvider->key()
#3 /var/www/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(32): Illuminate\\Encryption\\EncryptionServiceProvider->parseKey()
#4 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(869): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}()
#5 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(754): Illuminate\\Container\\Container->build()
#6 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\\Container\\Container->resolve()
#7 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\\Foundation\\Application->resolve()
#8 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(826): Illuminate\\Container\\Container->make()
#9 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(1027): Illuminate\\Foundation\\Application->make()
#10 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(947): Illuminate\\Container\\Container->resolveClass()
#11 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(908): Illuminate\\Container\\Container->resolveDependencies()
#12 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(754): Illuminate\\Container\\Container->build()
#13 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\\Container\\Container->resolve()
#14 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\\Foundation\\Application->resolve()
#15 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(826): Illuminate\\Container\\Container->make()
#16 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(205): Illuminate\\Foundation\\Application->make()
#17 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(179): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware()
#18 /var/www/public/index.php(62): Illuminate\\Foundation\\Http\\Kernel->terminate()
#19 {main}
"}
```

P.S. 
Really can't understand what's going on
I'm well familiar with docker, but in this case don't know what to do
Thanks everyone for your reply in advance 🤝

**Comment by plant7403** [comment]
not sure if the key messages are related to the issue, but i'm trying to investigate it
for the keys debug suggested to run ``` php artisan key:generate ```
on first try i found out that there was no ``` .env ``` file in the container, but ``` .env.docker ```, i copied it
then run ``` php artisan key:generate ``` it says:  **Application key set successfully.**
And now debug says: **The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.**

Not sure if the keys are related, i hope someone might know better
I'm just sharing my information, thank you

**Comment by dansup** [comment]
Can you confirm if there is a `APP_KEY` set in `.env`? Not that familiar with docker, maybe delete `.env.docker` and see if that helps?

**Comment by plant7403** [comment]
@dansup hmm, my tutorial says to leave APP_KEY empty in .env.docker file
They say it should generate by itself 😅
