### ISSUE TITLE
Failed to set memory limit to 134217728 bytes (Current memory usage is 169873408 bytes)

### ISSUE THREAD

**Issue by audioscavenger** [pixelfed/pixelfed#3036]
* release: dev branch
* context: docker-compose
* docker version: ubuntu latest
* command: `docker exec -it pixelfed php artisan import:cities`
* error: `Failed to set memory limit to 134217728 bytes (Current memory usage is 169873408 bytes)`
* complete stack trace:

```
Importing city data into database ...

Found 128769 cities to insert ...

 128769/128769 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

Successfully imported 128769 entries!

[2021-12-12 20:55:38] local.ERROR: Failed to set memory limit to 134217728 bytes (Current memory usage is 169873408 bytes) {"exception":"[object] (ErrorException(code: 0): Failed to set memory limit to 134217728 bytes (Current memory usage is 169873408 bytes) at /var/www/app/Console/Commands/ImportCities.php:140)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/app/Console/Commands/ImportCities.php(140): ini_set()
#2 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\ImportCities->handle()
#3 /var/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#5 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#6 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#7 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#8 /var/www/vendor/symfony/console/Command/Command.php(299): Illuminate\\Console\\Command->execute()
#9 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#10 /var/www/vendor/symfony/console/Application.php(978): Illuminate\\Console\\Command->run()
#11 /var/www/vendor/symfony/console/Application.php(295): Symfony\\Component\\Console\\Application->doRunCommand()
#12 /var/www/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
#13 /var/www/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run()
#14 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#15 /var/www/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#16 {main}
"}

   ErrorException

  Failed to set memory limit to 134217728 bytes (Current memory usage is 169873408 bytes)

  at app/Console/Commands/ImportCities.php:140
    136▕         $this->line('');
    137▕         $this->line('');
    138▕         $this->info('Successfully imported ' . $cityCount . ' entries!');
    139▕         $this->line('');
  ➜ 140▕         ini_set('memory_limit', $old_memory_limit);
    141▕         return;
    142▕     }
    143▕
    144▕     private function insertBuffer($buffer)

  1   app/Console/Commands/ImportCities.php:140
      ini_set()

      +13 vendor frames
  15  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

```

**Comment by dansup** [comment]
Fixed in latest commits!

**Comment by Barkoczy** [comment]
- release: latest
- context: docker-compose
- docker version: ubuntu latest
- command: docker-compose exec app php artisan import:cities
- error: Failed to set memory limit to 134217728 bytes (Current memory usage is 171970560 bytes)
- complete stack trace:

```bash
Importing city data into database ...

Found 128769 cities to insert ...

 128769/128769 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

Successfully imported 128769 entries!

[2022-08-30 20:41:45] production.ERROR: Failed to set memory limit to 134217728 bytes (Current memory usage is 171970560 bytes) {"exception":"[object] (ErrorException(code: 0): Failed to set memory limit to 134217728 bytes (Current memory usage is 171970560 bytes) at /var/www/app/Console/Commands/ImportCities.php:140)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/app/Console/Commands/ImportCities.php(140): ini_set()
#2 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\ImportCities->handle()
#3 /var/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#5 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#6 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#7 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#8 /var/www/vendor/symfony/console/Command/Command.php(298): Illuminate\\Console\\Command->execute()
#9 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#10 /var/www/vendor/symfony/console/Application.php(1024): Illuminate\\Console\\Command->run()
#11 /var/www/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#12 /var/www/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#13 /var/www/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run()
#14 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#15 /var/www/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#16 {main}
"}

   ErrorException

  Failed to set memory limit to 134217728 bytes (Current memory usage is 171970560 bytes)

  at app/Console/Commands/ImportCities.php:140
    136▕         $this->line('');
    137▕         $this->line('');
    138▕         $this->info('Successfully imported ' . $cityCount . ' entries!');
    139▕         $this->line('');
  ➜ 140▕         ini_set('memory_limit', $old_memory_limit);
    141▕         return;
    142▕     }
    143▕
    144▕     private function insertBuffer($buffer)

  1   app/Console/Commands/ImportCities.php:140
      ini_set()

      +13 vendor frames
  15  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```
