### ISSUE TITLE
Class 'BeyondCode\SelfDiagnosis\SelfDiagnosisServiceProvider' not found

### ISSUE THREAD

**Issue by Strubbl** [pixelfed/pixelfed#3045]
I get an error when running `php artisan migrate --force` on the latest dev commit c580c3dc5efd202d1bf7fff00cae6b2a9459e731

```
php artisan migrate --force
[2021-12-15 10:06:33] production.ERROR: Class 'BeyondCode\SelfDiagnosis\SelfDiagnosisServiceProvider' not found {"exception":"[object] (Error(code: 0): Class 'BeyondCode\\SelfDiagnosis\\SelfDiagnosisServiceProvider' not found at /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:735)
[stacktrace]
#0 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(669): Illuminate\\Foundation\\Application->resolveProvider()
#1 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\\Foundation\\Application->register()
#2 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(649): Illuminate\\Foundation\\ProviderRepository->load()
#3 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#4 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap()
#5 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith()
#6 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#7 /var/www/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#8 {main}
"} 

In Application.php line 735:
                                                                           
  Class 'BeyondCode\SelfDiagnosis\SelfDiagnosisServiceProvider' not found
```

**Comment by Strubbl** [comment]
The issue is still reproducible with dev commit 5442e232dc8d2255393c863ed7199d93b4b87ce9

**Comment by Strubbl** [comment]
As a workaround, i have added the line `RUN composer require beyondcode/laravel-self-diagnosis` to the `Dockerfile`

**Comment by dansup** [comment]
Did you run `composer install` or `composer update`? We're no longer using `laravel-self-diagnosis` anymore.

**Comment by Strubbl** [comment]
composer install is run by docker, see https://github.com/pixelfed/pixelfed/blob/dev/contrib/docker/Dockerfile.apache#L95

**Comment by Strubbl** [comment]
I could find a reference to the missing class:

```
/var/www# grep SelfDiagnosisServiceProvider -rn *
bootstrap/cache/packages.php:6:      0 => 'BeyondCode\\SelfDiagnosis\\SelfDiagnosisServiceProvider',
bootstrap/cache/services.php:26:    22 => 'BeyondCode\\SelfDiagnosis\\SelfDiagnosisServiceProvider',
bootstrap/cache/services.php:61:    10 => 'BeyondCode\\SelfDiagnosis\\SelfDiagnosisServiceProvider',
```

`rm /var/www/bootstrap/cache/*` helped to fix this

**Comment by leafonthewind** [comment]
I had a pixelfed install running, in docker, on a fairly old version of pixelfed code (2021-22 ish) and every attempted update to latest commits returned an error related to `SelfDiagnosisServiceProvider`.

Running `rm /var/www/bootstrap/cache/*` fixed this and allowed me to update to the latest commits.  (I had this data stored in a docker volume for app_bootstrap, so deleted it from the volume itself.). I guess the installer/upgrade process never cleaned up the old cache, so this manual step was required.

Thanks again!
