### ISSUE TITLE
Missing beyondcode/laravel-self-diagnosis dependency

### ISSUE THREAD

**Issue by SathyaBhat** [pixelfed/pixelfed#3150]
v0.11.2 seems to bring in a dependency for `beyondcode/laravel-self-diagnosis` but this is not present in `composer.json`. 

Without this, Pixelfed fails to start: 

```log
app_1     | [2022-01-10 19:06:17] production.ERROR: Class 'BeyondCode\SelfDiagnosis\SelfDiagnosisServiceProvider' not found {"exception":"[object] (Error(code: 0): Class 'BeyondCode\\SelfDiagnosis\\SelfDiagnosisServiceProvider' not found at /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:735)
app_1     | [stacktrace]
app_1     | #0 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(669): Illuminate\\Foundation\\Application->resolveProvider()
app_1     | #1 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\\Foundation\\Application->register()
app_1     | #2 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(649): Illuminate\\Foundation\\ProviderRepository->load()
app_1     | #3 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
app_1     | #4 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap()
app_1     | #5 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith()
app_1     | #6 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
app_1     | #7 /var/www/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
app_1     | #8 {main}
app_1     | "}
app_1     |
app_1     | In Application.php line 735:
app_1     |
app_1     |   Class 'BeyondCode\SelfDiagnosis\SelfDiagnosisServiceProvider' not found
```

A workaround would be to install manually using 

```php
composer require beyondcode/laravel-self-diagnosis
```

but would be better if the composer.json and the lock file is updated with this

**Comment by bigjdunham** [comment]
I did the suggested workaround and it works for me. Sad that it's not in the composer so it's automatic when we do a Docker build.

**Comment by Strubbl** [comment]
I already reported this issue in #3045.
The problem is old cache data in `/var/www/bootstrap/cache/`, which does not get deleted automatically - not even by one of the many artisan calls. There is a reference to the `SelfDiagnosisServiceProvider` hidden. Deleting the cache data fixes the problem. `laravel-self-diagnosis` is not a dependency anymore. For more details please have a look into the mentioned issue.

**Comment by SathyaBhat** [comment]
@Strubbl yep you are right.
