### ISSUE TITLE
 Undefined variable: id at /var/www/app/Http/Controllers/Api/ApiV1Controller.php:144

### ISSUE THREAD

**Issue by Strubbl** [pixelfed/pixelfed#3159]
I get this error after successful Oauth process with pixeldroid when i am redirected to the app. Is there anything i can do to fix this?

```
pixelfed-app-1     | 111.x.x.x - - [13/Jan/2022:23:42:47 +0000] "POST /oauth/token HTTP/1.0" 200 2151 "-" "okhttp/4.9.1"
pixelfed-app-1     | [2022-01-13 23:42:48] production.ERROR: Undefined variable: id {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined variable: id at /var/www/app/Http/Controllers/Api/ApiV1Controller.php:144)
pixelfed-app-1     | [stacktrace]
pixelfed-app-1     | #0 /var/www/app/Http/Controllers/Api/ApiV1Controller.php(144): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
pixelfed-app-1     | #1 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Api\\ApiV1Controller->verifyCredentials()
pixelfed-app-1     | #2 /var/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
pixelfed-app-1     | #3 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
pixelfed-app-1     | #4 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
pixelfed-app-1     | #5 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
pixelfed-app-1     | #6 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
pixelfed-app-1     | #7 /var/www/app/Http/Middleware/EmailVerificationCheck.php(35): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
pixelfed-app-1     | #8 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\EmailVerificationCheck->handle()
pixelfed-app-1     | #9 /var/www/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
pixelfed-app-1     | #10 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
pixelfed-app-1     | #11 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
pixelfed-app-1     | #12 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
pixelfed-app-1     | #13 /var/www/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
pixelfed-app-1     | #14 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle()
pixelfed-app-1     | #15 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
pixelfed-app-1     | #16 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
pixelfed-app-1     | #17 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
pixelfed-app-1     | #18 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
pixelfed-app-1     | #19 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
pixelfed-app-1     | #20 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
pixelfed-app-1     | #21 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
pixelfed-app-1     | #22 /var/www/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
pixelfed-app-1     | #23 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
pixelfed-app-1     | #24 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
pixelfed-app-1     | #25 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
pixelfed-app-1     | #26 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
pixelfed-app-1     | #27 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
pixelfed-app-1     | #28 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
pixelfed-app-1     | #29 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
pixelfed-app-1     | #30 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
pixelfed-app-1     | #31 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
pixelfed-app-1     | #32 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
pixelfed-app-1     | #33 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
pixelfed-app-1     | #34 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
pixelfed-app-1     | #35 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
pixelfed-app-1     | #36 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
pixelfed-app-1     | #37 /var/www/public/index.php(57): Illuminate\\Foundation\\Http\\Kernel->handle()
pixelfed-app-1     | #38 {main}
pixelfed-app-1     | "} 
pixelfed-app-1     | 111.x.x.x - - [13/Jan/2022:23:42:47 +0000] "GET /api/v1/accounts/verify_credentials HTTP/1.0" 500 12172 "-" "okhttp/4.9.1"

```

**Comment by dansup** [comment]
Fixed in #3161
