### ISSUE TITLE
Trying to edit settings via admin panel online throws an error in docker compose

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [pixelfed/pixelfed#3189]
I enabled editing settings online in admin panel but each time i try to save settings i get 500 internal server error and in docker i get this error:
```bash
app_1     | 2022-01-27T13:30:14.746904235Z 185.220.100.246 - - [27/Jan/2022:13:30:14 +0000] "POST /i/admin/settings HTTP/1.0" 500 13275 "https://photos.esmailelbob.xyz/i/admin/settings" "Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0"
app_1     | 2022-01-27T13:30:15.424983346Z 185.220.100.246 - - [27/Jan/2022:13:30:15 +0000] "GET /storage/avatars/default.png?v=0 HTTP/1.0" 304 213 "https://photos.esmailelbob.xyz/i/admin/settings" "Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0"
app_1     | 2022-01-27T13:33:43.134936141Z [2022-01-27 13:33:43] production.ERROR: The command "passport:keys" does not exist. {"userId":1,"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): The command \"passport:keys\" does not exist. at /var/www/vendor/laravel/framework/src/Illuminate/Console/Application.php:182)
app_1     | 2022-01-27T13:33:43.134983415Z [stacktrace]
app_1     | 2022-01-27T13:33:43.134990973Z #0 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(263): Illuminate\\Console\\Application->call()
app_1     | 2022-01-27T13:33:43.134996545Z #1 /var/www/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Foundation\\Console\\Kernel->call()
app_1     | 2022-01-27T13:33:43.135001757Z #2 /var/www/app/Http/Controllers/Admin/AdminSettingsController.php(154): Illuminate\\Support\\Facades\\Facade::__callStatic()
app_1     | 2022-01-27T13:33:43.135006496Z #3 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\AdminController->settingsHomeStore()
app_1     | 2022-01-27T13:33:43.135011222Z #4 /var/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
app_1     | 2022-01-27T13:33:43.135015859Z #5 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
app_1     | 2022-01-27T13:33:43.135020328Z #6 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
app_1     | 2022-01-27T13:33:43.135024994Z #7 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
app_1     | 2022-01-27T13:33:43.135029489Z #8 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
app_1     | 2022-01-27T13:33:43.135045660Z #9 /var/www/app/Http/Middleware/TwoFactorAuth.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
app_1     | 2022-01-27T13:33:43.135050696Z #10 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\TwoFactorAuth->handle()
app_1     | 2022-01-27T13:33:43.135055242Z #11 /var/www/app/Http/Middleware/DangerZone.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
app_1     | 2022-01-27T13:33:43.135059710Z #12 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\DangerZone->handle()
app_1     | 2022-01-27T13:33:43.135065391Z #13 /var/www/app/Http/Middleware/Admin.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
app_1     | 2022-01-27T13:33:43.135069870Z #14 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\Admin->handle()
app_1     | 2022-01-27T13:33:43.135074225Z #15 /var/www/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
app_1     | 2022-01-27T13:33:43.135078647Z #16 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle()
app_1     | 2022-01-27T13:33:43.135083248Z #17 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
app_1     | 2022-01-27T13:33:43.135087651Z #18 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
app_1     | 2022-01-27T13:33:43.135092004Z #19 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
app_1     | 2022-01-27T13:33:43.135096521Z #20 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
app_1     | 2022-01-27T13:33:43.135100920Z #21 /var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
app_1     | 2022-01-27T13:33:43.135105275Z #22 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
app_1     | 2022-01-27T13:33:43.135109555Z #23 /var/www/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
app_1     | 2022-01-27T13:33:43.135113860Z #24 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
app_1     | 2022-01-27T13:33:43.135118405Z #25 /var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
app_1     | 2022-01-27T13:33:43.135123118Z #26 /var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
app_1     | 2022-01-27T13:33:43.135127708Z #27 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
app_1     | 2022-01-27T13:33:43.135135909Z #28 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
app_1     | 2022-01-27T13:33:43.135140594Z #29 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
app_1     | 2022-01-27T13:33:43.135145050Z #30 /var/www/app/Http/Middleware/FrameGuard.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
app_1     | 2022-01-27T13:33:43.135149274Z #31 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\FrameGuard->handle()
app_1     | 2022-01-27T13:33:43.135153496Z #32 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
app_1     | 2022-01-27T13:33:43.135157890Z #33 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
app_1     | 2022-01-27T13:33:43.135162184Z #34 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
app_1     | 2022-01-27T13:33:43.135166456Z #35 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
app_1     | 2022-01-27T13:33:43.135170627Z #36 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
app_1     | 2022-01-27T13:33:43.135174989Z #37 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
app_1     | 2022-01-27T13:33:43.135179218Z #38 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
app_1     | 2022-01-27T13:33:43.135183470Z #39 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
app_1     | 2022-01-27T13:33:43.135187704Z #40 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
app_1     | 2022-01-27T13:33:43.135194396Z #41 /var/www/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
app_1     | 2022-01-27T13:33:43.135202413Z #42 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
app_1     | 2022-01-27T13:33:43.135210194Z #43 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
app_1     | 2022-01-27T13:33:43.135217596Z #44 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
app_1     | 2022-01-27T13:33:43.135224830Z #45 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
app_1     | 2022-01-27T13:33:43.135238816Z #46 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
app_1     | 2022-01-27T13:33:43.135246940Z #47 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
app_1     | 2022-01-27T13:33:43.135254865Z #48 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
app_1     | 2022-01-27T13:33:43.135262429Z #49 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
app_1     | 2022-01-27T13:33:43.135269968Z #50 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
app_1     | 2022-01-27T13:33:43.135277504Z #51 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
app_1     | 2022-01-27T13:33:43.135285349Z #52 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
app_1     | 2022-01-27T13:33:43.135292855Z #53 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
app_1     | 2022-01-27T13:33:43.135301547Z #54 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
app_1     | 2022-01-27T13:33:43.135309312Z #55 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
app_1     | 2022-01-27T13:33:43.135317124Z #56 /var/www/public/index.php(57): Illuminate\\Foundation\\Http\\Kernel->handle()
app_1     | 2022-01-27T13:33:43.135323889Z #57 {main}
app_1     | 2022-01-27T13:33:43.135330529Z "} 
app_1     | 2022-01-27T13:33:43.145011069Z 102.40.93.233 - - [27/Jan/2022:13:33:42 +0000] "POST /i/admin/settings HTTP/1.0" 500 13278 "https://photos.esmailelbob.xyz/i/admin/settings" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
app_1     | 2022-01-27T13:33:43.326802568Z 102.40.93.233 - - [27/Jan/2022:13:33:43 +0000] "GET /img/pixelfed-icon-color.svg HTTP/1.0" 304 213 "https://photos.esmailelbob.xyz/i/admin/settings" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
app_1     | 2022-01-27T13:33:43.329385314Z 102.40.93.233 - - [27/Jan/2022:13:33:43 +0000] "GET /js/manifest.js?id=7db827d654313dce4250 HTTP/1.0" 200 1036 "https://photos.esmailelbob.xyz/i/admin/settings" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
app_1     | 2022-01-27T13:33:43.484970497Z 102.40.93.233 - - [27/Jan/2022:13:33:43 +0000] "GET /fonts/fa-regular-400.woff2 HTTP/1.0" 304 214 "https://photos.esmailelbob.xyz/css/appdark.css?id=ccdcd84f1087f89bd7b2" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
app_1     | 2022-01-27T13:33:43.503267845Z 102.40.93.233 - - [27/Jan/2022:13:33:43 +0000] "GET /js/vendor.js?id=131c5e4445728ce4224a HTTP/1.0" 200 120131 "https://photos.esmailelbob.xyz/i/admin/settings" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
app_1     | 2022-01-27T13:33:43.643875289Z 102.40.93.233 - - [27/Jan/2022:13:33:43 +0000] "GET /storage/avatars/default.png?v=0 HTTP/1.0" 200 15025 "https://photos.esmailelbob.xyz/i/admin/settings" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"

```
i tried to rebuild docker image and flush data (docker-compose down -v) but still getting same error
___
latest build (git cloned it last night) and using docker last version on debian 11

**Comment by EsmailELBoBDev2** [comment]
I just saw https://github.com/pixelfed/pixelfed/issues/3188 so here is my output:
```bash
debian:~/docker-compose/pixelfed$ sudo docker-compose exec app php artisan tinker
Psy Shell v0.10.12 (PHP 7.4.27 — cli) by Justin Hileman
>>> decrypt('PAYLOAD HERE')
Illuminate\Contracts\Encryption\DecryptException with message 'The payload is invalid.'
>>> 
```

**Comment by EsmailELBoBDev2** [comment]
@dansup any updates on my case?

**Comment by dansup** [comment]
@EsmailELBoBDev2 Run `sudo docker-compose exec app php artisan passport:keys && sudo docker-compose exec app php artisan route:cache && sudo docker-compose exec app php artisan cache:clear`

**Comment by EsmailELBoBDev2** [comment]
Oh, it worked! Thanks

Could you tell me what was the issue so me in future or someone else can avoid it?

**Comment by dansup** [comment]
@EsmailELBoBDev2 As [described in the documentation](https://docs.pixelfed.org/running-pixelfed/installation.html#one-time-setup-tasks), you need to run `php artisan passport:keys` to generate the keys for the oauth apis.

**Comment by EsmailELBoBDev2** [comment]
Well, I followed a guide online and the only command mentioned was `php artisan key:generate` so this is why no matter how many times i run the command, It did not work :joy:.

Thanks!
