### ISSUE TITLE
Failed: App\Jobs\StatusPipeline\NewStatusPipeline

### ISSUE THREAD

**Issue by angristan** [pixelfed/pixelfed#333]
When making a new post, I see this in the horizon logs:

```
[2018-07-22 20:14:58][3] Processing: App\Jobs\StatusPipeline\NewStatusPipeline
[2018-07-22 20:14:58][3] Processing: App\Jobs\StatusPipeline\NewStatusPipeline
[2018-07-22 20:14:58][3] Failed:     App\Jobs\StatusPipeline\NewStatusPipeline
```

So far I don't see any issue from the website, but I am wondering why I get the issue.

**Comment by angristan** [comment]
Same for `App\Jobs\FollowPipeline\FollowPipeline`.

Here are some logs:

```php
[2018-07-22 20:30:29] production.ERROR: Call to undefined method Redis::connection() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method Redis::connection() at /srv/pixelfed/www/app/Jobs/FollowPipeline/FollowPipeline.php:55)
[stacktrace]
#0 [internal function]: App\\Jobs\\FollowPipeline\\FollowPipeline->handle()
#1 /srv/pixelfed/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#2 /srv/pixelfed/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 /srv/pixelfed/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#4 /srv/pixelfed/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#5 /srv/pixelfed/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#6 /srv/pixelfed/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\FollowPipeline\\FollowPipeline))
#7 /srv/pixelfed/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\FollowPipeline\\FollowPipeline))
#8 /srv/pixelfed/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#9 /srv/pixelfed/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\FollowPipeline\\FollowPipeline), false)
#10 /srv/pixelfed/www/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(83): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\RedisJob), Array)
#11 /srv/pixelfed/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(322): Illuminate\\Queue\\Jobs\\Job->fire()
#12 /srv/pixelfed/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(272): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#13 /srv/pixelfed/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#14 /srv/pixelfed/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon('redis', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#15 /srv/pixelfed/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'default')
#16 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#17 /srv/pixelfed/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#18 /srv/pixelfed/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#19 /srv/pixelfed/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#20 /srv/pixelfed/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#21 /srv/pixelfed/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#22 /srv/pixelfed/www/vendor/symfony/console/Command/Command.php(251): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#23 /srv/pixelfed/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#24 /srv/pixelfed/www/vendor/symfony/console/Application.php(886): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 /srv/pixelfed/www/vendor/symfony/console/Application.php(262): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 /srv/pixelfed/www/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 /srv/pixelfed/www/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 /srv/pixelfed/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#29 /srv/pixelfed/www/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 {main}
"}
```

**Comment by dansup** [comment]
@Angristan Just curious, do you have phpredis PHP extension installed?

**Comment by angristan** [comment]
Yes:

```sh
root@hinata ~# apt-cache policy php-redis
php-redis:
  Installed: 4.0.0-1+0~20180719123918.1+stretch~1.gbp24a357
  Candidate: 4.0.0-1+0~20180719123918.1+stretch~1.gbp24a357
  Version table:
 *** 4.0.0-1+0~20180719123918.1+stretch~1.gbp24a357 990
        990 https://packages.sury.org/php stretch/main amd64 Packages
        100 /var/lib/dpkg/status
     3.1.6-1+b1 -1
         -1 http://deb.debian.org/debian sid/main amd64 Packages
     3.1.1-1 990
        990 http://deb.debian.org/debian stretch/main amd64 Packages
```

**Comment by dansup** [comment]
@Angristan Ah okay, you need to decide if you want to use phpredis or predis. You can uninstall phpredis or update the config alias to use phpredis instead of predis. https://laravel.com/docs/5.6/redis#phpredis

**Comment by angristan** [comment]
I uninstalled php-redis, but I still have the issue!

**Comment by dansup** [comment]
@angristan I assume you fixed the issue?

**Comment by angristan** [comment]
I don't even remember where are the horizon logs...
