### ISSUE TITLE
video thumbnail job failed 

### ISSUE THREAD

**Issue by umarhadi** [pixelfed/pixelfed#3478]
when i upload a `.mp4` video, video thumbnail change to "no preview available".

![image](https://user-images.githubusercontent.com/31447862/168654721-aa3bc595-e209-412b-9f84-5c73fa62cce2.png)

and i'm check on horizon, `App\Jobs\VideoPipeline\VideoThumbnail` it's failed.

![image](https://user-images.githubusercontent.com/31447862/168656146-b404c0bb-bf29-434d-add4-7f68d4069f3b.png)

here's the stack trace:

```
Exception

UnexpectedValueException: The stream or file "/var/www/pixelfed/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied in /var/www/pixelfed/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146
--
Stack trace:
#0 /var/www/pixelfed/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(48): Monolog\Handler\StreamHandler->write()
#1 /var/www/pixelfed/vendor/monolog/monolog/src/Monolog/Logger.php(327): Monolog\Handler\AbstractProcessingHandler->handle()
#2 /var/www/pixelfed/vendor/monolog/monolog/src/Monolog/Logger.php(526): Monolog\Logger->addRecord()
#3 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Log/Logger.php(183): Monolog\Logger->info()
#4 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Log/Logger.php(130): Illuminate\Log\Logger->writeLog()
#5 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(624): Illuminate\Log\Logger->info()
#6 /var/www/pixelfed/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php(60): Illuminate\Log\LogManager->info()
#7 /var/www/pixelfed/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(207): Alchemy\BinaryDriver\ProcessRunner->run()
#8 /var/www/pixelfed/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(136): Alchemy\BinaryDriver\AbstractBinary->run()
#9 /var/www/pixelfed/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe/OptionsTester.php(61): Alchemy\BinaryDriver\AbstractBinary->command()
#10 /var/www/pixelfed/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe/OptionsTester.php(43): FFMpeg\FFProbe\OptionsTester->retrieveHelpOutput()
#11 /var/www/pixelfed/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php(237): FFMpeg\FFProbe\OptionsTester->has()
#12 /var/www/pixelfed/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php(206): FFMpeg\FFProbe->probe()
#13 /var/www/pixelfed/vendor/pbmedia/laravel-ffmpeg/src/FFMpeg/FFProbe.php(70): FFMpeg\FFProbe->streams()
#14 /var/www/pixelfed/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFMpeg.php(95): ProtoneMedia\LaravelFFMpeg\FFMpeg\FFProbe->streams()
#15 /var/www/pixelfed/vendor/pbmedia/laravel-ffmpeg/src/Drivers/PHPFFMpeg.php(124): FFMpeg\FFMpeg->open()
#16 /var/www/pixelfed/vendor/pbmedia/laravel-ffmpeg/src/MediaOpener.php(135): ProtoneMedia\LaravelFFMpeg\Drivers\PHPFFMpeg->open()
#17 /var/www/pixelfed/vendor/pbmedia/laravel-ffmpeg/src/MediaOpener.php(174): ProtoneMedia\LaravelFFMpeg\MediaOpener->getDriver()
#18 /var/www/pixelfed/app/Jobs/VideoPipeline/VideoThumbnail.php(56): ProtoneMedia\LaravelFFMpeg\MediaOpener->export()
#19 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\VideoPipeline\VideoThumbnail->handle()
#20 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#21 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#22 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#23 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call()
#24 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call()
#25 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#26 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#28 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\Bus\Dispatcher->dispatchNow()
#29 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#30 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#31 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\Pipeline\Pipeline->then()
#32 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#33 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#34 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(428): Illuminate\Queue\Jobs\Job->fire()
#35 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(378): Illuminate\Queue\Worker->process()
#36 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(172): Illuminate\Queue\Worker->runJob()
#37 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117): Illuminate\Queue\Worker->daemon()
#38 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Console\WorkCommand->runWorker()
#39 /var/www/pixelfed/vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\Queue\Console\WorkCommand->handle()
#40 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle()
#41 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#42 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#43 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#44 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call()
#45 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#46 /var/www/pixelfed/vendor/symfony/console/Command/Command.php(298): Illuminate\Console\Command->execute()
#47 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#48 /var/www/pixelfed/vendor/symfony/console/Application.php(1005): Illuminate\Console\Command->run()
#49 /var/www/pixelfed/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#50 /var/www/pixelfed/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#51 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\Component\Console\Application->run()
#52 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#53 /var/www/pixelfed/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#54 {main}

```

**Comment by zhangzhongwu666** [comment]
安装FFMpeg 扩展 并配置好路径

**Comment by dansup** [comment]
This looks like a permission issue! If you are still experiencing this, feel free to re-open.
