### ISSUE TITLE
Docker-compose clean install doesn't function

### ISSUE THREAD

**Issue by ggrensteiner** [pixelfed/pixelfed#3597]
On install of a new docker-compose instance using the supplied docker-compose.yml does not give a functional pixelfed_app container. It looks like the laravel code is broken on some kind of missing driver declaration on the db initialization.

```
+ cp -r storage.skel/app storage.skel/debugbar storage.skel/framework storage.skel/logs storage.skel/purify storage/
+ php /wait-for-db.php
Database is up
+ [[ ! -e storage/.docker.init ]]
+ echo 'Fresh installation, initializing database...'
+ gosu www-data php artisan key:generate
Fresh installation, initializing database...
[2022-07-31 13:08:29] production.ERROR: Trying to access array offset on value of type null {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at /var/www/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastManager.php:184)
```

The db container is online and working, connectivity works between the app and the db using the .env.production vars that I have entered.

**Comment by leafonthewind** [comment]
Thanks for this!  I was upgrading from 0.11.3 to 0.11.4 today and ran into this same error (pasted below for completeness).  This change in `.env.docker` solved it.

Much appreciated!

```bash
[2022-10-10 13:52:23] production.ERROR: Trying to access array offset on value of type null {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at /var/www/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastManager.php:184)
[stacktrace]
#0 /var/www/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastManager.php(184): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastManager.php(169): Illuminate\\Broadcasting\\BroadcastManager->resolve()
#2 /var/www/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastManager.php(158): Illuminate\\Broadcasting\\BroadcastManager->get()
#3 /var/www/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastManager.php(384): Illuminate\\Broadcasting\\BroadcastManager->driver()
#4 /var/www/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Broadcasting\\BroadcastManager->__call()
#5 /var/www/routes/channels.php(16): Illuminate\\Support\\Facades\\Facade::__callStatic()
#6 /var/www/app/Providers/BroadcastServiceProvider.php(19): require('/var/www/routes...')
#7 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Providers\\BroadcastServiceProvider->boot()
#8 /var/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#10 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#11 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#12 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(924): Illuminate\\Container\\Container->call()
#13 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(905): Illuminate\\Foundation\\Application->bootProvider()
#14 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
#15 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(906): array_walk()
#16 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#17 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
#18 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith()
#19 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#20 /var/www/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#21 {main}
"}

   ErrorException

  Trying to access array offset on value of type null

  at vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastManager.php:184
    180▕     protected function resolve($name)
    181▕     {
    182▕         $config = $this->getConfig($name);
    183▕
  ➜ 184▕         if (isset($this->customCreators[$config['driver']])) {
    185▕             return $this->callCustomCreator($config);
    186▕         }
    187▕
    188▕         $driverMethod = 'create'.ucfirst($config['driver']).'Driver';

      +5 vendor frames
  6   routes/channels.php:16
      Illuminate\Support\Facades\Facade::__callStatic()

  7   app/Providers/BroadcastServiceProvider.php:19
      require("/var/www/routes/channels.php")
```

**Comment by ghost** [comment]
For those wondering what the fix was, the issue is the comment on the BROADCAST_DRIVER line in the suggested .env file for pixelfed. Get rid of or move the comment to another line and this error will no longer happen.

**Comment by albjeremias** [comment]
So some tutorial:

> comment the line where it setting BROADCAST_DRIVER
` $ nano .env.docker`  

`  $ docker-compose build`

> setup the api_key
`  $ docker-compose run app php artisan key:generate`

`  $ docker-compose up`

I was getting this error:
````
app_1     | Stack trace:
app_1     | #0 /var/www/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(34): Illuminate\\Encryption\\Encrypter->__construct()
app_1     | #1 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(873): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}()
app_1     | #2 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\\Container\\Container->build()
app_1     | #3 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): Illuminate\\Container\\Container->resolve()
app_1     | #4 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\\Foundation\\Application->resolve()
app_1     | #5 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(836): Illuminate\\Con at /var/www/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:55)
app_1     | [stacktrace]
app_1     | #0 {main}
app_1     | "} 
````

my key was not working.. i had to make it manually:
` APP_KEY=base64:mmX77GbNWX2XsucdKe0XwtOKECta3h/B+p9NbH2jd0E=`

I had to remove the boostrap from the docker-compose (in two different places)
`#      - app-bootstrap:/var/www/bootstrap`

start the container:
`$ docker-compose up -d`

resintall all stuff:
`$ docker-compose exec app composer install --prefer-dist --no-interaction --no-ansi --optimize-autoloader`

https://docs.pixelfed.org/running-pixelfed/installation/#one-time-setup-tasks

run the migations:
`$ docker-compose exec app php artisan migrate`

run horizon
`$ docker-compose exec app php artisan horizon`


If you want to enable support for location data:
`$ docker-compose exec app php artisan import:cities`


```
 
  Failed to set memory limit to 134217728 bytes (Current memory usage is 171970560 bytes)
``` 
activate activitypub:
`$ docker-compose exec app php artisan instance:actor`

```
$ docker-compose exec app php artisan config:cache
$ docker-compose exec app php artisan route:cache
```

create your user to be an admin
`$ docker-compose exec app php artisan user:create`

got a 500 error, when searching for users on other instances on the search bar..

`$ docker-compose exec app php artisan passport:install`
