### ISSUE TITLE
Dockerfile has wrong php version (7.4) but composer requires 8

### ISSUE THREAD

**Issue by osresearch** [pixelfed/pixelfed#3810]
Change 18f3fcc66 set php to `"^8.0.2|^8.1"`, but the `Dockerfile.apache` is still based on `php:7.4-apache-bullseye`

**Comment by osresearch** [comment]
Attempting the easy fix against 4393780a4d3ff2ff30d26ec126fc2afc668fa420 leads to other problems that I don't know how to diagnose:

```
diff --git a/contrib/docker/Dockerfile.apache b/contrib/docker/Dockerfile.apache
index 206c86d1..5a6885a6 100644
--- a/contrib/docker/Dockerfile.apache
+++ b/contrib/docker/Dockerfile.apache
@@ -1,4 +1,4 @@
-FROM php:7.4-apache-bullseye
+FROM php:8.1-apache-bullseye
 
 # Use the default production configuration
 COPY contrib/docker/php.production.ini "$PHP_INI_DIR/php.ini"
```

Then `docker-compose up --build` leads to errors:
```
app_1     | [2022-11-20 17:09:29] production.ERROR: Class "Facade\Ignition\IgnitionServiceProvider" not found {"exception":"[object] (Error(code: 0): Class \"Facade\\Ignition\\IgnitionServiceProvider\" not found at /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:754)
app_1     | [stacktrace]
app_1     | #0 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(686): Illuminate\\Foundation\\Application->resolveProvider()
app_1     | #1 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\\Foundation\\Application->register()
app_1     | #2 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(666): Illuminate\\Foundation\\ProviderRepository->load()
app_1     | #3 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
app_1     | #4 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(242): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap()
app_1     | #5 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(383): Illuminate\\Foundation\\Application->bootstrapWith()
app_1     | #6 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(153): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
app_1     | #7 /var/www/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
app_1     | #8 {main}
app_1     | "} 
app_1     | 
app_1     | In Application.php line 754:
app_1     |                                                              
app_1     |   Class "Facade\Ignition\IgnitionServiceProvider" not found  
app_1     |                                                              
app_1     | 
```

**Comment by jimmybrancaccio** [comment]
This (#3740) _might_ fix it. Testing now...

Edit: It does not...😕

Edit 2: Running `composer install` and then `composer dump-autoload` does seem to fix the issue though.

**Comment by osresearch** [comment]
Applying the patches from #3740 and deleting the old docker volumes seem to have fixed the issue.  There might have been some old state in there that was preventing an actual clean build.

For dev instances I've found it much easier to use local `./data` directories instead of volumes so that it is easier to start from scratch or run multiple installs on the same system.  #3735 tries to do this, as well as run the one-time startup tasks automatically so that the operator doesn't have to
