### ISSUE TITLE
openning "Directory" page in admin panel throws error

### ISSUE THREAD

**Issue by murtezayesil** [pixelfed/pixelfed#3913]
I am was checking every tab in admin panel (instance.domain.tld/i/admin) to see what they contain. Directory page shows nothing after seemingly loading for a long time (spinning loading indicator spins about 5 minutes or longer).

After checking `$PIXELFED_PATH/storage/logs/laravel.log` I saw the below error being thrown every single time:
```
[2022-12-09 19:41:46] production.ERROR: Undefined array key 0 {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined array key 0 at /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Collections/Collection.php:1699)
[stacktrace]
#0 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(259): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(1699): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /usr/share/webapps/pixelfed/app/Http/Controllers/Admin/AdminDirectoryController.php(60): Illuminate\\Support\\Collection->offsetGet()
#3 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\AdminController->directoryInitialData()
#4 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#5 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#6 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#7 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Routing\\Route->run()
#8 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#9 /usr/share/webapps/pixelfed/app/Http/Middleware/TwoFactorAuth.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\TwoFactorAuth->handle()
#11 /usr/share/webapps/pixelfed/app/Http/Middleware/DangerZone.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\DangerZone->handle()
#13 /usr/share/webapps/pixelfed/app/Http/Middleware/Admin.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\Admin->handle()
#15 /usr/share/webapps/pixelfed/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle()
#17 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#19 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#21 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
#23 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#25 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#27 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#28 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#30 /usr/share/webapps/pixelfed/app/Http/Middleware/FrameGuard.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\FrameGuard->handle()
#32 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#34 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Pipeline\\Pipeline->then()
#36 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack()
#37 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute()
#38 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute()
#39 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch()
#40 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#41 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#43 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#45 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#46 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#48 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#49 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#51 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#53 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then()
#55 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#56 /usr/share/webapps/pixelfed/public/index.php(57): Illuminate\\Foundation\\Http\\Kernel->handle()
#57 {main}
"}
```

```
=======================
 Pixelfed Instance Diagnostic v0.2 
=======================
Troubleshooting

Bootstrap: Writable ✅
Storage: Writable ✅
DATABASE Ping: Pong! Connected to DB "pixelfed" ✅
REDIS Ping: Pong! Connected to Redis ✅
ACTIVITYPUB instance actor created: ✅ true
ACTIVITYPUB instance actor cached: ❌ false
OAUTH enabled: ✅ true
OAUTH token_expiration 365 days
OAUTH public key exists: ✅ true
OAUTH private key exists: ✅ true

Important Information

Version: 0.11.4-54e00237
Database: mysql (10.6.11-MariaDB-0ubuntu0.22.04.1)
APP_URL: https://images.yesil.club
APP_DOMAIN: images.yesil.club
ADMIN_DOMAIN: images.yesil.club
SESSION_DOMAIN: images.yesil.club

PHP Variables

PHP: 8.1.2-1ubuntu2.9
PHP INI memory_limit: 128M
PHP INI post_max_size: 1000M
PHP INI upload_max_filesize: 12M
PHP INI max_file_uploads: 2000
PHP INI max_execution_time: 600
PHP INI max_input_time: 60
PHP INI file_uploads (On): 1
PHP INI - SECURITY allow_url_fopen (true): 1
PHP INI - SECURITY allow_url_include (false):
PHP INI - SECURITY expose_php (false):
PHP INI - SECURITY display_errors (false): Off
PHP INI - SECURITY display_startup_errors (false):
PHP INI - SECURITY log_errors (true): 1
PHP INI - SECURITY ignore_repeated_errors (false):
PHP INI - SECURITY disable_functions:

Pixelfed Variables (No Secrets)

CONFIG	VARIABLE NAME	DETAILS
APP	APP_NAME	"Yesil Club"
APP	APP_ENV	"production"
APP	APP_DEBUG	❌ false
APP	APP_URL	"https://images.yesil.club"
APP	APP_LOCALE	"en"
APP	APP_FALLBACK_LOCALE	"en"
BROADCASTING	BROADCAST_DRIVER	"log"
CACHE	CACHE_DRIVER	"redis"
CAPTCHA	CAPTCHA_ENABLED	❌ false
DATABASE	DB_CONNECTION	"mysql"
DATABASE	REDIS_CLIENT	"predis"
EXP	EXP_LC	❌ false
EXP	EXP_TOP	❌ false
EXP	EXP_POLLS	✅ true
EXP	EXP_CPT	❌ false
EXP	EXP_GPS	❌ false
EXP	EXP_EMC	✅ true
FEDERATION	ACTIVITY_PUB	❌ false
FEDERATION	AP_OUTBOX	❌ false
FEDERATION	AP_INBOX	❌ false
FEDERATION	AP_SHAREDINBOX	❌ false
FEDERATION	AP_REMOTE_FOLLOW	❌ false
FEDERATION	ACTIVITYPUB_DELIVERY_TIMEOUT	"30"
FEDERATION	ACTIVITYPUB_DELIVERY_CONCURRENCY	"10"
FEDERATION	AP_LOGGER_ENABLED	❌ false
FEDERATION	ATOM_FEEDS	✅ true
FEDERATION	REMOTE_AVATARS	✅ true
FEDERATION	NODEINFO	✅ true
FEDERATION	WEBFINGER	✅ true
FEDERATION	PF_NETWORK_TIMELINE	✅ true
FEDERATION	PF_NETWORK_TIMELINE_DAYS_FALLOFF	2
FEDERATION	CUSTOM_EMOJI	✅ true
FEDERATION	CUSTOM_EMOJI_MAX_SIZE	"2000000"
FILESYSTEMS	FILESYSTEM_DRIVER	"local"
FILESYSTEMS	FILESYSTEM_CLOUD	"s3"
HASHING	BCRYPT_COST	"10"
HORIZON	HORIZON_PREFIX	"horizon-"
HORIZON	HORIZON_MEMORY_LIMIT	"64"
HORIZON	HORIZON_BALANCE_STRATEGY	"auto"
HORIZON	HORIZON_MIN_PROCESSES	"1"
HORIZON	HORIZON_MAX_PROCESSES	"20"
HORIZON	HORIZON_SUPERVISOR_MEMORY	"64"
HORIZON	HORIZON_SUPERVISOR_TRIES	"3"
HORIZON	HORIZON_SUPERVISOR_NICE	"0"
HORIZON	HORIZON_SUPERVISOR_TIMEOUT	"300"
HORIZON	HORIZON_DARKMODE	❌ false
IMAGE	IMAGE_DRIVER	"gd"
INSTANCE	INSTANCE_DESCRIPTION	"Pixelfed - Photo sharing for everyone"
INSTANCE	INSTANCE_CONTACT_FORM	❌ false
INSTANCE	INSTANCE_CONTACT_MAX_PER_DAY	"1"
INSTANCE	INSTANCE_DISCOVER_PUBLIC	❌ false
INSTANCE	EXP_LOOPS	❌ false
INSTANCE	INSTANCE_PUBLIC_HASHTAGS	❌ false
INSTANCE	INSTANCE_CONTACT_EMAIL	"images@emails.yesil.club"
INSTANCE	INSTANCE_PUBLIC_LOCAL_TIMELINE	❌ false
INSTANCE	INSTANCE_NETWORK_TIMELINE_CACHED	
INSTANCE	INSTANCE_NETWORK_TIMELINE_CACHE_DROPOFF	100
INSTANCE	INSTANCE_NETWORK_TIMELINE_CACHE_MAX_HOUR_INGEST	6
INSTANCE	PAGE_404_HEADER	"Sorry, this page isn't available."
INSTANCE	PAGE_404_BODY	"The link you followed may be broken, or the page may have been removed. <a href="/">Go back to Pixelfed.</a>"
INSTANCE	PAGE_503_HEADER	"Service Unavailable"
INSTANCE	PAGE_503_BODY	"Our service is in maintenance mode, please try again later."
INSTANCE	BANNED_USERNAMES	""
INSTANCE	USERNAME_REMOTE_FORMAT	"@"
INSTANCE	USERNAME_REMOTE_CUSTOM_TEXT	""
INSTANCE	STORIES_ENABLED	✅ true
INSTANCE	RESTRICTED_INSTANCE	❌ false
INSTANCE	OAUTH_TOKEN_DAYS	"365"
INSTANCE	OAUTH_REFRESH_DAYS	"400"
INSTANCE	OAUTH_PAT_ENABLED	❌ false
INSTANCE	OAUTH_PAT_ID	""
INSTANCE	ENABLE_COVID_LABEL	✅ true
INSTANCE	COVID_LABEL_URL	"https://www.who.int/emergencies/diseases/novel-coronavirus-2019/advice-for-public"
INSTANCE	COVID_LABEL_ORG	"visit the WHO website"
INSTANCE	ENABLE_CONFIG_CACHE	❌ false
LDAP	LDAP_CONNECTION	"default"
LDAP	LDAP_LOGGING	✅ true
LDAP	LDAP_CACHE	❌ false
LOGGING	LOG_CHANNEL	"stack"
LOGGING	LOG_LEVEL (stack)	"debug"
MAIL	MAIL_DRIVER	"smtp"
MAIL	MAIL_HOST	"mailer.yesil.club"
MAIL	MAIL_PORT	"465"
MAIL	MAIL_FROM_ADDRESS	"images@emails.yesil.club"
MAIL	MAIL_FROM_NAME	"Pixelfed on Yesil Club"
MAIL	MAIL_ENCRYPTION	"tls"
MEDIA	MEDIA_EXIF_DATABASE	❌ false
PIXELFED	ADMIN_DOMAIN	"images.yesil.club"
PIXELFED	APP_DOMAIN	"images.yesil.club"
PIXELFED	MEMORY_LIMIT	"1024M"
PIXELFED	OPEN_REGISTRATION	❌ false
PIXELFED	MAX_ACCOUNT_SIZE (KB)	"1000000"
PIXELFED	MAX_PHOTO_SIZE (KB)	"15000"
PIXELFED	MAX_AVATAR_SIZE (KB)	"5000"
PIXELFED	MAX_CAPTION_LENGTH	"500"
PIXELFED	MAX_BIO_LENGTH	"500"
PIXELFED	MAX_NAME_LENGTH	"30"
PIXELFED	MIN_PASSWORD_LENGTH	"8"
PIXELFED	MAX_ALBUM_LENGTH	"10"
PIXELFED	ENFORCE_EMAIL_VERIFICATION	✅ true
PIXELFED	IMAGE_QUALITY (1-100)	"80"
PIXELFED	ACCOUNT_DELETION	✅ true
PIXELFED	ACCOUNT_DELETE_AFTER	❌ false
PIXELFED	PF_ENABLE_CLOUD	✅ true
PIXELFED	PF_MAX_USERS	1000
PIXELFED	PF_OPTIMIZE_IMAGES	✅ true
PIXELFED	PF_OPTIMIZE_VIDEOS	✅ true
PIXELFED	PF_USER_INVITES	✅ true
PIXELFED	PF_USER_INVITES_TOTAL_LIMIT	"0"
PIXELFED	PF_USER_INVITES_DAILY_LIMIT	"0"
PIXELFED	PF_USER_INVITES_MONTHLY_LIMIT	"3"
PIXELFED	PF_MAX_COLLECTION_LENGTH	"100"
PIXELFED	MEDIA_TYPES	"image/jpeg,image/png,image/gif"
PIXELFED	LIMIT_ACCOUNT_SIZE	✅ true
PIXELFED	IMPORT_INSTAGRAM	❌ false
PIXELFED	IMPORT_INSTAGRAM_POST_LIMIT	"100"
PIXELFED	IMPORT_INSTAGRAM_SIZE_LIMIT	"5000"
PIXELFED	OAUTH_ENABLED	✅ true
PIXELFED	PF_BOUNCER_ENABLED	❌ false
PIXELFED	PF_MEDIA_FAST_PROCESS	✅ true
PIXELFED	PF_MEDIA_MAX_ALTTEXT_LENGTH	"1000"
PURIFY	RESTRICT_HTML_TYPES	BROKEN
QUEUE	QUEUE_DRIVER	"redis"
SESSION	SESSION_DRIVER	"database"
SESSION	SESSION_LIFETIME	"86400"
SESSION	SESSION_DOMAIN	"images.yesil.club"
TRUSTEDPROXY	TRUST_PROXIES	"*"
========= END =========
```
---
Also no activity pub actor is cached. Is it due to me not following any person from any instance just yet. It is currently a single person instance and I didn't open it to registration just yet.

**Comment by mitexleo** [comment]
You need to enable Activity Public First... Otherwise federation won't work
