### ISSUE TITLE
Portfolio SQL query missing 'id' in 'group by' clause (Postgres-based installation)

### ISSUE THREAD

**Issue by stanclai** [pixelfed/pixelfed#4044]
When trying to watch user's portfolio I get an error `column "media.id" must appear in the GROUP BY clause or be used in an aggregate function` in statement `select "status_id" from "media" where "profile_id" = 2 and "status_id" is not null group by "status_id" order by "id" desc limit 50`.

I'm using [latest `dev`](https://github.com/pixelfed/pixelfed/commit/6165f509cf2edd1e326419807c92ef1830dd1cae) with Postgresql database.

Solution: 

```diff
diff --git a/app/Http/Controllers/PortfolioController.php b/app/Http/Controllers/PortfolioController.php
index 5890f2d0..2c00c082 100644
--- a/app/Http/Controllers/PortfolioController.php
+++ b/app/Http/Controllers/PortfolioController.php
@@ -184,7 +184,7 @@ class PortfolioController extends Controller
             return DB::table('media')
             ->whereProfileId($id)
             ->whereNotNull('status_id')
-            ->groupBy('status_id')
+            ->groupBy('status_id', 'id')
             ->orderByDesc('id')
             ->take(50)
             ->pluck('status_id');
```

After applying this patch the problem was resolved. IDK, though, if it's applicable for all cases (I mean, MySQL, for example).

Please see corresponding log lines below:

````
[2022-12-30 07:38:08] production.ERROR: SQLSTATE[42803]: Grouping error: 7 ERROR:  column "media.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...tus_id" is not null group by "status_id" order by "id" desc ...
                                                             ^ (SQL: select "status_id" from "media" where "profile_id" = 2 and "status_id" is not null group by "status_id" order by "id" desc limit 50) {"userId":
2,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42803): SQLSTATE[42803]: Grouping error: 7 ERROR:  column \"media.id\" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...tus_id\" is not null group by \"status_id\" order by \"id\" desc ...
                                                             ^ (SQL: select \"status_id\" from \"media\" where \"profile_id\" = 2 and \"status_id\" is not null group by \"status_id\" order by \"id\" desc limit 50
) at /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760)
[stacktrace]
#0 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\\Database\\Connection->runQueryCallback()
#1 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php(422): Illuminate\\Database\\Connection->run()
#2 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2650): Illuminate\\Database\\Connection->select()
#3 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2864): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3174): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#5 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2866): Illuminate\\Database\\Query\\Builder->onceWithColumns()
#6 /var/lib/pixelfed/app/Http/Controllers/PortfolioController.php(190): Illuminate\\Database\\Query\\Builder->pluck()
#7 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(391): App\\Http\\Controllers\\PortfolioController->App\\Http\\Controllers\\{closure}()
#8 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(419): Illuminate\\Cache\\Repository->remember()
#9 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Illuminate\\Cache\\CacheManager->__call()
#10 /var/lib/pixelfed/app/Http/Controllers/PortfolioController.php(191): Illuminate\\Support\\Facades\\Facade::__callStatic()
#11 /var/lib/pixelfed/app/Http/Controllers/PortfolioController.php(166): App\\Http\\Controllers\\PortfolioController->getRecentFeed()
#12 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\PortfolioController->getFeed()
#13 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#14 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#15 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#16 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Routing\\Route->run()
#17 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#18 /var/lib/pixelfed/app/Http/Middleware/Localization.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\Localization->handle()
#20 /var/lib/pixelfed/app/Http/Middleware/TwoFactorAuth.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\TwoFactorAuth->handle()
#22 /var/lib/pixelfed/app/Http/Middleware/EmailVerificationCheck.php(35): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\EmailVerificationCheck->handle()
#24 /var/lib/pixelfed/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle()
#26 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#28 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#30 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
#32 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#34 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#36 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#37 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#39 /var/lib/pixelfed/app/Http/Middleware/FrameGuard.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\FrameGuard->handle()
#41 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#43 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Pipeline\\Pipeline->then()
#45 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack()
#46 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute()
#47 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute()
#48 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch()
#49 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#50 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#52 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#54 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#55 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#57 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#58 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#60 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#62 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then()
#64 /var/lib/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#65 /var/lib/pixelfed/public/index.php(57): Illuminate\\Foundation\\Http\\Kernel->handle()
#66 {main}
````

**Comment by Zir0h** [comment]
it also seems to work if you just remove the groupBy line :sweat_smile:

**Comment by zeeZ** [comment]
The query as it is written is also technically invalid in MySQL and only works in MariaDB because `ONLY_FULL_GROUP_BY` is not enabled there by default and ignores the error. `id` must be contained in the `group by` clause if it is to be used in `order by`
