### ISSUE TITLE
docker compose exec app php artisan video:thumbnail  > error "Unable to probe"

### ISSUE THREAD

**Issue by saschafoerster** [pixelfed/pixelfed#4198]
I was trying out all CLI from the pixelfed documentation. 

I am using a docker installation of Pixelfed, mostly based on this instructions: 
https://alejandro.criadoperez.com/blog/Install_pixelfed_with_docker

I am on the branch "dev" right now. 

When trying out this CLI: 
`docker compose exec app php artisan video:thumbnail`

I got this error message: 
```
root@vm: docker compose exec app php artisan video:thumbnail
[2023-02-18 16:58:00] production.ERROR: Unable to probe /var/www/storage/app/https://bonn.social/system/media_attachments/files/109/723/184/129/065/923/original/f03df293db3bde28.mp4 {"exception":"[object] (FFMpeg\\Exception\\RuntimeException(code: 0): Unable to probe /var/www/storage/app/https://bonn.social/system/media_attachments/files/109/723/184/129/065/923/original/f03df293db3bde28.mp4 at /var/www/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php:254)
[stacktrace]
#0 /var/www/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php(200): FFMpeg\\FFProbe->probe()
#1 /var/www/vendor/pbmedia/laravel-ffmpeg/src/FFMpeg/FFProbe.php(70): FFMpeg\\FFProbe->streams()
#2 /var/www/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFMpeg.php(93): ProtoneMedia\\LaravelFFMpeg\\FFMpeg\\FFProbe->streams()
#3 /var/www/vendor/pbmedia/laravel-ffmpeg/src/Drivers/PHPFFMpeg.php(124): FFMpeg\\FFMpeg->open()
#4 /var/www/vendor/pbmedia/laravel-ffmpeg/src/MediaOpener.php(156): ProtoneMedia\\LaravelFFMpeg\\Drivers\\PHPFFMpeg->open()
#5 /var/www/vendor/pbmedia/laravel-ffmpeg/src/MediaOpener.php(195): ProtoneMedia\\LaravelFFMpeg\\MediaOpener->getDriver()
#6 /var/www/app/Jobs/VideoPipeline/VideoThumbnail.php(58): ProtoneMedia\\LaravelFFMpeg\\MediaOpener->export()
#7 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\VideoPipeline\\VideoThumbnail->handle()
#8 /var/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#10 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#11 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call()
#12 /var/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#13 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#14 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /var/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#16 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php(88): Illuminate\\Bus\\Dispatcher->dispatchNow()
#17 /var/www/app/Console/Commands/VideoThumbnail.php(49): App\\Jobs\\VideoPipeline\\VideoThumbnail::dispatchNow()
#18 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\VideoThumbnail->handle()
#19 /var/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#20 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#21 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#22 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call()
#23 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#24 /var/www/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute()
#25 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(153): Symfony\\Component\\Console\\Command\\Command->run()
#26 /var/www/vendor/symfony/console/Application.php(1022): Illuminate\\Console\\Command->run()
#27 /var/www/vendor/symfony/console/Application.php(314): Symfony\\Component\\Console\\Application->doRunCommand()
#28 /var/www/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun()
#29 /var/www/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#30 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run()
#31 /var/www/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#32 {main}

[previous exception] [object] (Alchemy\\BinaryDriver\\Exception\\ExecutionFailureException(code: 0): ffprobe failed to execute command '/usr/bin/ffprobe' '/var/www/storage/app/https://bonn.social/system/media_attachments/files/109/723/184/129/065/923/original/f03df293db3bde28.mp4' '-show_streams' '-print_format' 'json':

Error Output:

 ffprobe version 4.3.5-0+deb11u1 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
/var/www/storage/app/https://bonn.social/system/media_attachments/files/109/723/184/129/065/923/original/f03df293db3bde28.mp4: No such file or directory
 at /var/www/vendor/php-ffmpeg/php-ffmpeg/src/Alchemy/BinaryDriver/ProcessRunner.php:94)
[stacktrace]
#0 /var/www/vendor/php-ffmpeg/php-ffmpeg/src/Alchemy/BinaryDriver/ProcessRunner.php(72): Alchemy\\BinaryDriver\\ProcessRunner->doExecutionFailure()
#1 /var/www/vendor/php-ffmpeg/php-ffmpeg/src/Alchemy/BinaryDriver/AbstractBinary.php(207): Alchemy\\BinaryDriver\\ProcessRunner->run()
#2 /var/www/vendor/php-ffmpeg/php-ffmpeg/src/Alchemy/BinaryDriver/AbstractBinary.php(136): Alchemy\\BinaryDriver\\AbstractBinary->run()
#3 /var/www/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php(252): Alchemy\\BinaryDriver\\AbstractBinary->command()
#4 /var/www/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php(200): FFMpeg\\FFProbe->probe()
#5 /var/www/vendor/pbmedia/laravel-ffmpeg/src/FFMpeg/FFProbe.php(70): FFMpeg\\FFProbe->streams()
#6 /var/www/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFMpeg.php(93): ProtoneMedia\\LaravelFFMpeg\\FFMpeg\\FFProbe->streams()
#7 /var/www/vendor/pbmedia/laravel-ffmpeg/src/Drivers/PHPFFMpeg.php(124): FFMpeg\\FFMpeg->open()
#8 /var/www/vendor/pbmedia/laravel-ffmpeg/src/MediaOpener.php(156): ProtoneMedia\\LaravelFFMpeg\\Drivers\\PHPFFMpeg->open()
#9 /var/www/vendor/pbmedia/laravel-ffmpeg/src/MediaOpener.php(195): ProtoneMedia\\LaravelFFMpeg\\MediaOpener->getDriver()
#10 /var/www/app/Jobs/VideoPipeline/VideoThumbnail.php(58): ProtoneMedia\\LaravelFFMpeg\\MediaOpener->export()
#11 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\VideoPipeline\\VideoThumbnail->handle()
#12 /var/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#14 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#15 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call()
#16 /var/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#17 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#18 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#20 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php(88): Illuminate\\Bus\\Dispatcher->dispatchNow()
#21 /var/www/app/Console/Commands/VideoThumbnail.php(49): App\\Jobs\\VideoPipeline\\VideoThumbnail::dispatchNow()
#22 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\VideoThumbnail->handle()
#23 /var/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#24 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#25 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#26 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call()
#27 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#28 /var/www/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute()
#29 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(153): Symfony\\Component\\Console\\Command\\Command->run()
#30 /var/www/vendor/symfony/console/Application.php(1022): Illuminate\\Console\\Command->run()
#31 /var/www/vendor/symfony/console/Application.php(314): Symfony\\Component\\Console\\Application->doRunCommand()
#32 /var/www/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun()
#33 /var/www/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#34 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run()
#35 /var/www/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#36 {main}
"} 

   FFMpeg\Exception\RuntimeException 

  Unable to probe /var/www/storage/app/https://bonn.social/system/media_attachments/files/109/723/184/129/065/923/original/f03df293db3bde28.mp4

  at vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php:254
    250▕ 
    251▕         try {
    252▕             $output = $this->ffprobe->command($commands);
    253▕         } catch (ExecutionFailureException $e) {
  ➜ 254▕             throw new RuntimeException(sprintf('Unable to probe %s', $pathfile), $e->getCode(), $e);
    255▕         }
    256▕ 
    257▕         if ($parseIsToDo) {
    258▕             $data = $this->parser->parse($type, $output);

      +11 vendor frames 
  12  app/Jobs/VideoPipeline/VideoThumbnail.php:58
      ProtoneMedia\LaravelFFMpeg\MediaOpener::export()

      +10 vendor frames 
  23  app/Console/Commands/VideoThumbnail.php:49
      App\Jobs\VideoPipeline\VideoThumbnail::dispatchNow()
```

When I start bash into the pixelfed-container, I can find this folder but it is empty: 
Docker. /var/www/storage/app/https://bonn.social/system/media_attachments/files/109/723/184/129/065/923/original/
There is no file f03df293db3bde28.mp4

I also use docker volumes in the virtual machine, so I can make backups more easily. When I go to the folder: 
VM: /home/pixelfed/docker-volumes/storage/app
I don't see any https://

I guess the problem is that docker is not able to use :// as folder name. But this is just a guess.

**Comment by saschafoerster** [comment]
I don't know what happened, but this issue is gone with latest v0.11.13 and the new docker setup.
