### ISSUE TITLE
backup:run only works with mysql backend

### ISSUE THREAD

**Issue by gunchleoc** [pixelfed/pixelfed#5088]
When running `php artisan backup:run`, Pixelfed assumes that MariaDB or MySQL is being used as the database backend, because it tried to call `mysqldump`.

So, the command cannot be used for PostgreSQL. This is not documented.

Error output:

```
www-data@pixelfed:~/pixelfed$ php artisan backup:run 
Starting backup...
Dumping database pixelfed...
Backup failed because: The dump process failed with a none successful exitcode.
Exitcode
========
127: Command not found

Output
======
<no output>

Error Output
============
sh: 1: mysqldump: not found
.
#0 /var/www/pixelfed/vendor/spatie/db-dumper/src/DbDumper.php(194): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully()
#1 /var/www/pixelfed/vendor/spatie/db-dumper/src/Databases/MySql.php(161): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul()
#2 /var/www/pixelfed/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(284): Spatie\DbDumper\Databases\MySql->dumpToFile()
#3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}()
#4 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(600): array_map()
#5 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(777): Illuminate\Support\Arr::map()
#6 /var/www/pixelfed/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(249): Illuminate\Support\Collection->map()
#7 /var/www/pixelfed/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(189): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases()
#8 /var/www/pixelfed/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(163): Spatie\Backup\Tasks\Backup\BackupJob->createBackupManifest()
#9 /var/www/pixelfed/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(65): Spatie\Backup\Tasks\Backup\BackupJob->run()
#10 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Spatie\Backup\Commands\BackupCommand->handle()
#11 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#12 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#13 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#14 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#15 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\Container\Container->call()
#16 /var/www/pixelfed/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
#17 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\Component\Console\Command\Command->run()
#18 /var/www/pixelfed/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(28): Illuminate\Console\Command->run()
#19 /var/www/pixelfed/vendor/symfony/console/Application.php(1096): Spatie\Backup\Commands\BaseCommand->run()
#20 /var/www/pixelfed/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#21 /var/www/pixelfed/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#22 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run()
#23 /var/www/pixelfed/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#24 {main}
Backup failed because: The dump process failed with a none successful exitcode.
Exitcode
========
127: Command not found

Output
======
<no output>

Error Output
============
sh: 1: mysqldump: not found
```

**Comment by dansup** [comment]
Database backups use a 3rd party package, you can find the configuration in `config/backup.php`

Change this line as you need https://github.com/pixelfed/pixelfed/blob/dev/config/backup.php#L69
