### ISSUE TITLE
Docker: issue with variables expansion from .env in docker-compose.yml when using podman-compose

### ISSUE THREAD

**Issue by offerman** [pixelfed/pixelfed#5175]
Following the description for running Pixelfed in a Docker container here:
https://jippi.github.io/pixelfed-docs-next/pr-preview/pr-1/running-pixelfed/docker/installation.html
However, using podman-compose (version 1.0.6) and podman (version 4.9.4-dev) on CentOS Stream 8 here rather than Docker.

There appears to be an issue with the propagation/expansion of variables from the .env file in the docker-compose.yml file, as I get the following message when running 'podman-compose up -d':

```
[root@services pixelfed]# podman-compose up -d
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 4.9.4-dev
Traceback (most recent call last):
  File "/usr/bin/podman-compose", line 11, in <module>
    load_entry_point('podman-compose==1.0.6', 'console_scripts', 'podman-compose')()
  File "/usr/lib/python3.6/site-packages/podman_compose.py", line 2940, in main
    podman_compose.run()
  File "/usr/lib/python3.6/site-packages/podman_compose.py", line 1420, in run
    self._parse_compose_file()
  File "/usr/lib/python3.6/site-packages/podman_compose.py", line 1620, in _parse_compose_file
    mnt_dict = get_mnt_dict(self, cnt, volume)
  File "/usr/lib/python3.6/site-packages/podman_compose.py", line 504, in get_mnt_dict
    volume = parse_short_mount(volume, basedir)
  File "/usr/lib/python3.6/site-packages/podman_compose.py", line 174, in parse_short_mount
    raise ValueError("unknown mount option " + opt)
ValueError: unknown mount option /etc/nginx/conf.d
```

Substituting the value by hand in docker-compose.yml solves this issue (and makes podman-compose complain in a similar way about the next line:

```
    volumes:
      - "${DOCKER_PROXY_HOST_DOCKER_SOCKET_PATH}:/tmp/docker.sock:ro"
#     - "${DOCKER_ALL_HOST_CONFIG_ROOT_PATH}/proxy/conf.d:/etc/nginx/conf.d"
      - "./docker-compose-state/config/proxy/conf.d:/etc/nginx/conf.d"
      - "${DOCKER_ALL_HOST_CONFIG_ROOT_PATH}/proxy/vhost.d:/etc/nginx/vhost.d"
```
I don't see anything wrong with the syntax or the variables used, so not sure whether this is a problem with the .env & docker-compose.yml combo or maybe an (incompatibility) issue with podman-compose. 
Has anyone else tried running the Pixelfed Docker image with podman-compose?

UPDATE: 
The issue appears to be in the variable syntax in docker-compose.yml: there are several assignments using ':?error', which isn't evaluating correctly. Changing this to ':?err' as specified in the Compose Specification doesn't help however. 
Removing the ':?error' part "solves" the issue.

**Comment by dansup** [comment]
cc @jippi
