### ISSUE TITLE
Docker-Deployment does not work - "first-time-setup" causes error in database initialization

### ISSUE THREAD

**Issue by jacotec** [pixelfed/pixelfed#5209]
I just wanted to give Pixelfed a try using the Docker installation. Although following strictly the docs, all containers started, the access does not work. The Docker logs are showing some kind of internal error regarding the database initialization:

```
pix.majak.de-worker      | [entrypoint / entrypoint.sh] - ============================================================
pix.majak.de-worker      | [entrypoint / entrypoint.sh] - Executing [/docker/entrypoint.d/11-first-time-setup.sh]
pix.majak.de-worker      | [entrypoint / entrypoint.sh] - ============================================================
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - Sourcing /var/www/.env
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - ❓ Waiting for database to be ready
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - Sourcing /var/www/.env
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - ✅ Successfully connected to database
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - Command [run-as-runtime-user php artisan key:generate] has already run once before (remove file [/var/www/storage/docker/once/key:generate] to run it again)
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - Command [run-as-runtime-user php artisan storage:link] has already run once before (remove file [/var/www/storage/docker/once/storage:link] to run it again)
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - 👷 Running [php artisan migrate --force] as [www-data]
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stdout)
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stdout) INFO  Running migrations.
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stdout)
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stdout) 2021_08_30_050137_add_software_column_to_instances_table .......... 6ms FAIL
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) [2024-07-05 11:51:59] production.ERROR: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'software' (Connection: mysql, SQL: alter table `instances` add `software` varchar(191) null, add `user_count` int unsigned null, add `status_count` int unsigned null, add `last_crawled_at` timestamp null) {"exception":"[object] (Illuminate\Database\QueryException(code: 42S21): SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'software' (Connection: mysql, SQL: alter table `instances` add `software` varchar(191) null, add `user_count` int unsigned null, add `status_count` int unsigned null, add `last_crawled_at` timestamp null) at /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:829)
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) [stacktrace]
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #0 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(783): Illuminate\Database\Connection->runQueryCallback()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #1 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(576): Illuminate\Database\Connection->run()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #2 /var/www/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(110): Illuminate\Database\Connection->statement()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #3 /var/www/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(602): Illuminate\Database\Schema\Blueprint->build()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #4 /var/www/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(444): Illuminate\Database\Schema\Builder->build()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #5 /var/www/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(355): Illuminate\Database\Schema\Builder->table()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #6 /var/www/database/migrations/2021_08_30_050137_add_software_column_to_instances_table.php(17): Illuminate\Support\Facades\Facade::__callStatic()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #7 /var/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(493): AddSoftwareColumnToInstancesTable->up()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #8 /var/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(410): Illuminate\Database\Migrations\Migrator->runMethod()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #9 /var/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(419): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #10 /var/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(216): Illuminate\Database\Migrations\Migrator->runMigration()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #11 /var/www/vendor/laravel/framework/src/Illuminate/Console/View/Components/Task.php(37): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #12 /var/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(756): Illuminate\Console\View\Components\Task->render()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #13 /var/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(216): Illuminate\Database\Migrations\Migrator->write()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stdout)
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #14 /var/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(181): Illuminate\Database\Migrations\Migrator->runUp()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stdout) Illuminate\Database\QueryException
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stdout)
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #15 /var/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(124): Illuminate\Database\Migrations\Migrator->runPending()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #16 /var/www/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(90): Illuminate\Database\Migrations\Migrator->run()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stdout) SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'software' (Connection: mysql, SQL: alter table `instances` add `software` varchar(191) null, add `user_count` int unsigned null, add `status_count` int unsigned null, add `last_crawled_at` timestamp null)
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stdout)
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #17 /var/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(633): Illuminate\Database\Console\Migrations\MigrateCommand->Illuminate\Database\Console\Migrations\{closure}()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #18 /var/www/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(83): Illuminate\Database\Migrations\Migrator->usingConnection()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stdout) at vendor/laravel/framework/src/Illuminate/Database/Connection.php:829
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #19 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Database\Console\Migrations\MigrateCommand->handle()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #20 /var/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #21 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #22 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #23 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #24 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\Container\Container->call()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #25 /var/www/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #26 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\Component\Console\Command\Command->run()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #27 /var/www/vendor/symfony/console/Application.php(1096): Illuminate\Console\Command->run()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #28 /var/www/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #29 /var/www/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #30 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #31 /var/www/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #32 {main}
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr)
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) [previous exception] [object] (PDOException(code: 42S21): SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name
'software' at /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:587)
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) [stacktrace]
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #0 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(587): PDOStatement->execute()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #1 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(816): Illuminate\Database\Connection->Illuminate\Database\{closure}()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #2 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(783): Illuminate\Database\Connection->runQueryCallback()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #3 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(576): Illuminate\Database\Connection->run()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stdout) 825▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stdout) 826▕                 );
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #4 /var/www/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(110): Illuminate\Database\Connection->statement()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stdout) 827▕             }
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #5 /var/www/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(602): Illuminate\Database\Schema\Blueprint->build()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stdout) 828▕
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #6 /var/www/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(444): Illuminate\Database\Schema\Builder->build()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stdout) ➜ 829▕             throw new QueryException(
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #7 /var/www/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(355): Illuminate\Database\Schema\Builder->table()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stdout) 830▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #8 /var/www/database/migrations/2021_08_30_050137_add_software_column_to_instances_table.php(17): Illuminate\Support\Facades\Facade::__callStatic()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stdout) 831▕             );
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stdout) 832▕         }
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #9 /var/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(493): AddSoftwareColumnToInstancesTable->up()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stdout) 833▕     }
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #10 /var/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(410): Illuminate\Database\Migrations\Migrator->runMethod()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stdout)
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stdout) +9 vendor frames
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #11 /var/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(419): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stdout) 10  database/migrations/2021_08_30_050137_add_software_column_to_instances_table.php:17
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #12 /var/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(216): Illuminate\Database\Migrations\Migrator->runMigration()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stdout) Illuminate\Support\Facades\Facade::__callStatic()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #13 /var/www/vendor/laravel/framework/src/Illuminate/Console/View/Components/Task.php(37): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stdout)
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stdout) +24 vendor frames
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stdout) 35  artisan:35
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #14 /var/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(756): Illuminate\Console\View\Components\Task->render()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stdout) Illuminate\Foundation\Console\Kernel::handle()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #15 /var/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(216): Illuminate\Database\Migrations\Migrator->write()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #16 /var/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(181): Illuminate\Database\Migrations\Migrator->runUp()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #17 /var/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(124): Illuminate\Database\Migrations\Migrator->runPending()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #18 /var/www/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(90): Illuminate\Database\Migrations\Migrator->run()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #19 /var/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(633): Illuminate\Database\Console\Migrations\MigrateCommand->Illuminate\Database\Console\Migrations\{closure}()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #20 /var/www/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(83): Illuminate\Database\Migrations\Migrator->usingConnection()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #21 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Database\Console\Migrations\MigrateCommand->handle()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #22 /var/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #23 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #24 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #25 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #26 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\Container\Container->call()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #27 /var/www/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #28 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\Component\Console\Command\Command->run()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #29 /var/www/vendor/symfony/console/Application.php(1096): Illuminate\Console\Command->run()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #30 /var/www/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #31 /var/www/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #32 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #33 /var/www/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) #34 {main}
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - (stderr) "}
pix.majak.de-worker      | [entrypoint / 11-first-time-setup.sh] - ERROR - ❌ Error! 
```

**Comment by scarpentier** [comment]
I'm experiencing the same error. 

There's something wrong with the `2021_08_30_050137_add_software_column_to_instances_table` migration.

Were you able to fix it?

**Comment by scarpentier** [comment]
I can see the columns are already in the database. I was able to continue the installation by tricking the `php artisan migrate` command in skipping this particular migration:
```
INSERT INTO pixelfed_prod.migrations
(id, migration, batch)
VALUES(124, '2021_08_30_050137_add_software_column_to_instances_table', 1);
```
