### ISSUE TITLE
Image uploads not working, SQLSTATE not null violation with Postgresql

### ISSUE THREAD

**Issue by poVoq** [pixelfed/pixelfed#5217]
I just tried setting up a new instance of Pixeldfed 0.12.3 with a Postgres 16 database and everything seems to be working except that I can't upload images.

When I try uploading an image I get the following error in the browser console (edited to replace domain):
```
XHRPOST
https://example.com/api/compose/v0/media/upload
[HTTP/2 500  60ms]
```
followed by:
`Uncaught (in promise) SweetAlert: 2nd argument ('undefined') is invalid vendor.js:2:2562289`

And the actual response to the first error seems to be this:
```
error	'SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "caption" of relation "media" violates not-null constraint\nDETAIL: Failing row contains (119, null, 714627581718265857, 1, public/m/_v2/714627581718265857/3781ba7d4-1bb9dc/fBQROYvqllvI/23..., null, null, null, null, 1, image/webp, 23988, null, null, 2024-07-11 22:12:00, 2024-07-11 22:12:00, null, null, null, 3a7db0ff6785d065ee86f81ac1da22d7299b8826b0f283e8f17a44bcfa6ad98f, null, null, null, null, null, null, null, f, 3, f, null, null, nu…null, null). (Connection: pgsql, SQL: insert into "media" ("status_id", "profile_id", "user_id", "media_path", "original_sha256", "size", "mime", "filter_class", "filter_name", "version", "updated_at", "created_at") values (?, 714627581718265857, 1, public/m/_v2/714627581718265857/3781ba7d4-1bb9dc/fBQROYvqllvI/23CtSTgmV6Mqjfl0o1A2ElMJOxxR3awMjavDlKS8.webp, 3a7db0ff6785d065ee86f81ac1da22d7299b8826b0f283e8f17a44bcfa6ad98f, 23988, image/webp, ?, ?, 3, 2024-07-11 22:12:00, 2024-07-11 22:12:00) returning "id")' 
```

Maybe I am overlooking something as I am pretty new to Pixelfed, but this looks like a bug to me? Maybe Postgresql specific?

Thanks for the help!

**Comment by poVoq** [comment]
Is there a recommended way to migrate to MariaDB if Postgresql support is broken?

**Comment by poVoq** [comment]
I switched to MariaDB and this issue seems to be gone, so I guess that is confirmation that this is a Postgresql 16 incompatibility bug.

**Comment by Lord0fBytes** [comment]
I am having the same issue as well. I am not able to switch to MariaDB since I am using YUNOHost, but is this a bug within Postgresql?

0.12.3~ynh1 - Pixelfed
13.15 - Postgres
8.2.21 - PHP
11.13.0 - Laravel


> 'SQLSTATE[23502]:  Not null violation: 7 ERROR:  null value in column "caption" of  relation "media" violates not-null constraint\nDETAIL:  Failing row  contains (10, null, 725038823714533377, 1,  public/m/_v2/725533377/0e43b1202-69768b/2kkmT6KkgeBk/bP...,  null, null, null, null, 1, image/jpeg, 3621469, null, null, 2024-08-02  21:54:22, 2024-08-02 21:54:22, null, null, null,  80479df84b45b4b6a503abccbd35ba558fed1c123c54806c, null,  null, null, null, null, null, null, f, 3, f, null, null, n…ull, null).  (Connection: pgsql, SQL: insert into "media" ("status_id", "profile_id",  "user_id", "media_path", "original_sha256", "size", "mime",  "filter_class", "filter_name", "version", "updated_at", "created_at")  values (?, 725038823714533377, 1,  public/m/_v2/7233377/0e43b1202-69768b/2kkmT6KkgeBk/bPg4HRN8iAcUF4pLIEVvyExdmfQRmFeCy.jpg,  80479df84b45b4b3abccbd35ba558fed1c123c54806c,  3621469, image/jpeg, ?, ?, 3, 2024-08-02 21:54:22, 2024-08-02 21:54:22)  returning "id")'

^ truncated some ID's for privacy.

**Comment by GotBas** [comment]
Hi, same problem here. 

**Tests**
_With native web UI_

> If i post a photo without type any text anywhere, it's works. 
> In 'media' table it's seems i  have a blank in `caption` filed

_With native android app_

> I can add a photo without enter a caption, but posting failed 

_With Pixeldroid app_
> UI ask for caption before post description. 
> If it's empty, posting fail
> If i type a caption it's ok
> In 'media' table i have the caption text in `caption` filed


**Configuration**
- Pixelfed 0.12.3
- MariaDB 10.11.6-MariaDB-0+deb12u1
- PHP 8.2.20
- Laravel 11.21.0

**Log**

> [2024-09-04 12:13:39] production.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'caption' cannot be null (Connection: mysql, SQL: insert into `media` (`status_id`, `profile_id`, `user_id`, `media_path`, `original_sha256`, `size`, `mime`, `caption`, `filter_class`, `filter_name`, `updated_at`, `created_at`) values (?, 735934089308161, 1, public/m/_v2/735934042089308161/586f75268-5004eb/zUlXGD9Vh2Sh/khATui5HkeGI1x4iS7AnkYcTAK85Uenxq1N.jpg, 6c1ef99317cf888621d8b17c12ff98fb05053993ece15a5780deca20, 2462508, image/jpeg, **?**, ?, ?, 2024-09-04 12:13:39, 2024-09-04 12:13:39)) {"userId":1,"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'caption' cannot be null (Connection: mysql, SQL: insert into `media` (`status_id`, `profile_id`, `user_id`, `media_path`, `original_sha256`, `size`, `mime`, `caption`, `filter_class`, `filter_name`, `updated_at`, `created_at`) values (?, 7359340308161, 1, public/m/_v2/735934042089161/586f75-5004eb/zUlVh2Sh/khATui5HkejcPFFGI1S7AnkYcTAK85Uenxq1N.jpg, 99449317cf888621d8b17c12ff98fb05053993b0c5dece15a5780deca20, 2462508, image/jpeg, **?**, ?, ?, 2024-09-04 12:13:39, 2024-09-04 12:13:39)) at /<my_server_path>/vendor/laravel/framework/src/Illuminate/Database/Connection.php:825)


In database, Caption field in `media` table is `not nullable` and his default value is `null`

**Comment by GotBas** [comment]
Test of a bypass method to see the impact : change nullable state of media.caption

`desc media;`

| Field             | Type                | Null      | Key              |  Default            | Extra          |
| :---------      | :------	        | :------	 | :------	 | :------	 | :------	|  
| caption           | text                | NO   |     | NULL    |                |

`ALTER TABLE media MODIFY caption text null;`

| Field             | Type                | Null      | Key              |  Default            | Extra          |
| :---------      | :------	        | :------	 | :------	 | :------	 | :------	|  
| caption           | text                | YES  |     | NULL    |                |

_With native android app_
- I can add a photo without enter a caption, it works 👍  

_With Pixeldroid app_
- UI ask for caption before post description.
- If it's empty, it's work 👍 
- Alternative text "without description" 👍 

_With native web UI_
- UI seems working 👍

**Comment by vt520** [comment]
> Test of a bypass method to see the impact : change nullable state of media.caption
> 
> `desc media;`
> 
> Field	Type	Null	Key	Default	Extra
> caption	text	NO		NULL	
> `ALTER TABLE media MODIFY caption text null;`
> 
> Field	Type	Null	Key	Default	Extra
> caption	text	YES		NULL	
> _With native android app_
> 
> * I can add a photo without enter a caption, it works 👍
> 
> _With Pixeldroid app_
> 
> * UI ask for caption before post description.
> * If it's empty, it's work 👍
> * Alternative text "without description" 👍
> 
> _With native web UI_
> 
> * UI seems working 👍

I couldn't get your command to work, but the idea is sound.  I got it working using the following in psql

```sql 
alter table media alter column caption drop not null;
```

**Comment by paboum** [comment]
I get the same error on MariaDB: `SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'caption' cannot be null (Connection: mysql, SQL: insert into `statuses` (`profile_id`, `caption`, `rendered`, `visibility`, `scope`, `in_reply_to_profile_id`, `id`, `updated_at`, `created_at`) values (<redacted>, ?, ?, direct, direct, <redacted>...))`
```
Package: mariadb-server
Version: 1:10.11.6-0+deb12u1

Package: php
Version: 2:8.2+93

pixelfed release v0.12.3

Laravel Framework 11.13.0
``

**Comment by agardelein** [comment]
The [fix](https://github.com/YunoHost-Apps/pixelfed_ynh/pull/271) from @OniriCorpe worked for me on Postgresql 18.8, by directly modifying the database:
```
sudo -u postgres psql -d pixelfed
alter table media alter column caption drop not null;
```

**Comment by solarisfire** [comment]
Postgres 17 here, brand new instance set up today and instagram import is throwing this error:

<pre>
[2025-01-08 17:00:02] production.ERROR: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "rendered" of relation "statuses" violates not-null constraint
DETAIL:  Failing row contains (1000001240420148, null, Flat-lays are tricky! 😅, null, 782576219769733121, null, null, null, f, unlisted, f, 0, 0, null, null, t, null, null, null, 2024-04-20 18:20:12, 2025-01-08 17:00:02, null, null, unlisted, photo, null, f, null, null, null, null, null). (Connection: pgsql, SQL: insert into "statuses" ("profile_id", "caption", "type", "scope", "visibility", "id", "created_at", "updated_at") values (782576219769733121, Flat-lays are tricky! 😅, photo, unlisted, unlisted, 1000001240420148, 2024-04-20 18:20:12, 2025-01-08 17:00:02)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"rendered\" of relation \"statuses\" violates not-null constraint
DETAIL:  Failing row contains (1000001240420148, null, Flat-lays are tricky! 😅, null, 782576219769733121, null, null, null, f, unlisted, f, 0, 0, null, null, t, null, null, null, 2024-04-20 18:20:12, 2025-01-08 17:00:02, null, null, unlisted, photo, null, f, null, null, null, null, null). (Connection: pgsql, SQL: insert into \"statuses\" (\"profile_id\", \"caption\", \"type\", \"scope\", \"visibility\", \"id\", \"created_at\", \"updated_at\") values (782576219769733121, Flat-lays are tricky! 😅, photo, unlisted, unlisted, 1000001240420148, 2024-04-20 18:20:12, 2025-01-08 17:00:02)) at /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php:825)
[stacktrace]
#0 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php(779): Illuminate\\Database\\Connection->runQueryCallback()
#1 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php(560): Illuminate\\Database\\Connection->run()
#2 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php(524): Illuminate\\Database\\Connection->statement()
#3 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3748): Illuminate\\Database\\Connection->insert()
#4 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(2051): Illuminate\\Database\\Query\\Builder->insert()
#5 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1335): Illuminate\\Database\\Eloquent\\Builder->__call()
#6 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1163): Illuminate\\Database\\Eloquent\\Model->performInsert()
#7 /usr/share/webapps/pixelfed/app/Console/Commands/TransformImports.php(116): Illuminate\\Database\\Eloquent\\Model->save()
#8 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\TransformImports->handle()
#9 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#11 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#12 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\\Container\\BoundMethod::call()
#13 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\\Container\\Container->call()
#14 /usr/share/webapps/pixelfed/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute()
#15 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\\Component\\Console\\Command\\Command->run()
#16 /usr/share/webapps/pixelfed/vendor/symfony/console/Application.php(1094): Illuminate\\Console\\Command->run()
#17 /usr/share/webapps/pixelfed/vendor/symfony/console/Application.php(342): Symfony\\Component\\Console\\Application->doRunCommand()
#18 /usr/share/webapps/pixelfed/vendor/symfony/console/Application.php(193): Symfony\\Component\\Console\\Application->doRun()
#19 /usr/share/webapps/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(198): Symfony\\Component\\Console\\Application->run()
#20 /usr/share/webapps/pixelfed/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#21 {main}
</pre>

**Comment by nozense** [comment]
This might be the same problem: 

I have a newly installed pixelfed server on docker, using postgres.

Trying to sen messages generates this: 

```
2025-01-14 13:33:11.163 CET [81] ERROR:  null value in column "rendered" of relation "statuses" violates not-null constraint

2025-01-14 13:33:11.163 CET [81] DETAIL:  Failing row contains (784759274499006498, null, banan, null, 784717504846540801, null, null, null, f, direct, f, 0, 0, null, null, t, null, 784723833251909633, null, 2025-01-14 12:33:11, 2025-01-14 12:33:11, null, null, direct, null, null, f, null, null, null, null, null).

2025-01-14 13:33:11.163 CET [81] STATEMENT:  insert into "statuses" ("profile_id", "caption", "visibility", "scope", "in_reply_to_profile_id", "id", "updated_at", "created_at") values ($1, $2, $3, $4, $5, $6, $7, $8)
```

Using theses "hacks" seems to solve the problem, but why is it null to begin with? or set to not null?

```
alter table statuses alter column rendered drop not null;
alter table statuses alter column caption drop not null;
```

Is the offical way to go mysql or is something broken?

**Comment by nozense** [comment]
Maybe this should be part of #2727

**Comment by solarisfire** [comment]
Feels like PostgreSQL should be removed from the documentation and it should state only MariaDB is supported 😅

**Comment by lonenomad** [comment]
I solved this by running the following:

```
# sudo -u postgres psql
psql=# \c db_pixelfed
psql=# ALTER TABLE statuses ALTER COLUMN caption DROP NOT NULL;
psql=# ALTER TABLE statuses ALTER COLUMN rendered DROP NOT NULL;
psql=# \q
```

**Comment by deptadapt** [comment]
I am also getting this error. This error happened when the account I followed reblogged, and is the only activity so far on this brand new instance.

Under failed jobs in the Horizon dashboard:
App\Jobs\InboxPipeline\ActivityHandler

[pixelfed-errors.txt](https://github.com/user-attachments/files/19725184/pixelfed-errors.txt)

Pixelfed 0.12.5
PostgreSQL 15.12
PHP 8.4.6
