### ISSUE TITLE
File upload with UTF-8 characters fails

### ISSUE THREAD

**Issue by dereckson** [pixelfed/pixelfed#558]
When I tried to upload Tunnel_du_métro_fantôme_de_Charleroi.jpg, that failed with the following stacktrace:

```
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'count(): Parame...', '/var/wwwroot/de...', 100, Array)            
#1 /var/wwwroot/default/app/Http/Controllers/StatusController.php(100): count(NULL)                                                                            
#2 [internal function]: App\\Http\\Controllers\\StatusController->store(Object(Illuminate\\Http\\Request))                                                     
#3 /var/wwwroot/default/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)                                 
#4 /var/wwwroot/default/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('store', Arra
y)                                                                                                                                                             
#5 /var/wwwroot/default/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\
Routing\\Route), Object(App\\Http\\Controllers\\StatusController), 'store')     
```

Or with the other UI:

```
[2018-11-14 20:22:59] production.ERROR: The file "" does not exist {"userId":1,"email":"dereckson@espace-win.org","exception":"[object] (Symfony\\Component\\Ht
tpFoundation\\File\\Exception\\FileNotFoundException(code: 0): The file \"\" does not exist at /var/wwwroot/default/vendor/symfony/http-foundation/File/MimeTyp
e/MimeTypeGuesser.php:116)                                                                                                                                     
[stacktrace]                                                                                                                                                   
#0 /var/wwwroot/default/vendor/symfony/http-foundation/File/File.php(79): Symfony\\Component\\HttpFoundation\\File\\MimeType\\MimeTypeGuesser->guess('')       
#1 /var/wwwroot/default/vendor/symfony/http-foundation/File/File.php(58): Symfony\\Component\\HttpFoundation\\File\\File->getMimeType()                        
#2 /var/wwwroot/default/vendor/laravel/framework/src/Illuminate/Http/FileHelpers.php(60): Symfony\\Component\\HttpFoundation\\File\\File->guessExtension()     #3 /var/wwwroot/default/vendor/laravel/framework/src/Illuminate/Http/UploadedFile.php(35): Illuminate\\Http\\UploadedFile->hashName()                          
#4 /var/wwwroot/default/app/Http/Controllers/Api/BaseApiController.php(172): Illuminate\\Http\\UploadedFile->store('public/m/a674a9...')                       
#5 [internal function]: App\\Http\\Controllers\\Api\\BaseApiController->uploadMedia(Object(Illuminate\\Http\\Request))                                         
#6 /var/wwwroot/default/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)                                 
#7 /var/wwwroot/default/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('uploadMedia'
, Array)                                                                                                                                                       
#8 /var/wwwroot/default/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\
Routing\\Route), Object(App\\Http\\Controllers\\ApiController), 'uploadMedia')    
```

Encoding of the filename is UTF-8. When I created a symbolic link to tunnel.jpg and selected this one for upload, all worked fine.

**Comment by dansup** [comment]
@dereckson Interesting, I can't reproduce this locally or on pixelfed.social. I don't think this has to do with filename because pixelfed does not preserve the filename during upload, it generates a random filename.

Can you try the same filename with a different image?

**Comment by dereckson** [comment]
The same file with tunnel.jpg uploads, another file with the same name doesn't.

If the bug is difficult to reproduce, I see meanwhile something already actionnable: to throw an exception as soon as the app detects there is no file to handle in the second stack trace, or when the array is null in the first.

**Comment by trwnh** [comment]
Could it maybe have something to do with the hashing function and accented characters?

**Comment by dansup** [comment]
@dereckson What OS/php version are you using? I was able to successfully upload an image with that filename both locally and on a production instance.

@trwnh No it shouldn't, it generates a file hash and doesn't use the original filename at all.

**Comment by dereckson** [comment]
Debian Stretch with C.UTF-8 as locale (not en_US.UTF-8)

**Comment by dereckson** [comment]
I tried to create more media upload failure opportunity, like launching a server limited to 1 byte upload. Similar error occurs.

So, a more general bug could be we don't have a stack trace pointing to the source of a media upload failure, also silently ignored in the logs.
