### ISSUE TITLE
Federation issue with PostgreSQL

### ISSUE THREAD

**Issue by captainark** [pixelfed/pixelfed#677]
Hi!

I tried activating federation on my Pixelfed instance today, to no avail.

I'm using a PostgreSQL database.

At first, remote follows were not working, and I was getting an error message regarding the length constraint of the `bio` column from the `profiles` table.

I do not have logs of the error anymore, but I was able to get around it by issuing the following SQL query :
```sql
alter table profiles alter column bio type character varying;
```

After that, remote follows were working, but posts still do not federate.

I'm now getting the following error message :
```
[2018-12-25 16:26:57] local.ERROR: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "profile_id" violates not-null constraint
DETAIL:  Failing row contains (3, null, null, null, null, null, null, 2018-12-25 16:26:57, 2018-12-25 16:26:57, null, null, null). (SQL: insert into "notifications" ("updated_at", "created_at") values (2018-12-25 16:26:57, 2018-12-25 16:26:57) returning "id") {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"profile_id\" violates not-null constraint
DETAIL:  Failing row contains (3, null, null, null, null, null, null, 2018-12-25 16:26:57, 2018-12-25 16:26:57, null, null, null). (SQL: insert into \"notifications\" (\"updated_at\", \"created_at\") values (2018-12-25 16:26:57, 2018-12-25 16:26:57) returning \"id\") at /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"profile_id\" violates not-null constraint
DETAIL:  Failing row contains (3, null, null, null, null, null, null, 2018-12-25 16:26:57, 2018-12-25 16:26:57, null, null, null). at /opt/www/pixelfed/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119, PDOException(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"profile_id\" violates not-null constraint
DETAIL:  Failing row contains (3, null, null, null, null, null, null, 2018-12-25 16:26:57, 2018-12-25 16:26:57, null, null, null). at /opt/www/pixelfed/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)
[stacktrace]
#0 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('insert into \"no...', Array, Object(Closure))
#1 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('insert into \"no...', Array, Object(Closure))
#2 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php(304): Illuminate\\Database\\Connection->select('insert into \"no...', Array, false)
#3 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/PostgresProcessor.php(20): Illuminate\\Database\\Connection->selectFromWriteConnection('insert into \"no...', Array)
#4 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2615): Illuminate\\Database\\Query\\Processors\\PostgresProcessor->processInsertGetId(Object(Illuminate\\Database\\Query\\Builder), 'insert into \"no...', Array, 'id')
#5 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1318): Illuminate\\Database\\Query\\Builder->insertGetId(Array, 'id')
#6 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(823): Illuminate\\Database\\Eloquent\\Builder->__call('insertGetId', Array)
#7 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(788): Illuminate\\Database\\Eloquent\\Model->insertAndSetId(Object(Illuminate\\Database\\Eloquent\\Builder), Array)
#8 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(651): Illuminate\\Database\\Eloquent\\Model->performInsert(Object(Illuminate\\Database\\Eloquent\\Builder))
#9 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(417): Illuminate\\Database\\Eloquent\\Model->save()
#10 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1027): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\{closure}(Object(App\\Notification))
#11 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(418): tap(Object(App\\Notification), Object(Closure))
#12 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->firstOrCreate(Array)
#13 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1608): Illuminate\\Database\\Eloquent\\Model->forwardCallTo(Object(Illuminate\\Database\\Eloquent\\Builder), 'firstOrCreate', Array)
#14 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1620): Illuminate\\Database\\Eloquent\\Model->__call('firstOrCreate', Array)
#15 /opt/www/pixelfed/app/Util/ActivityPub/Inbox.php(216): Illuminate\\Database\\Eloquent\\Model::__callStatic('firstOrCreate', Array)
#16 /opt/www/pixelfed/app/Util/ActivityPub/Inbox.php(71): App\\Util\\ActivityPub\\Inbox->handleFollowActivity()
#17 /opt/www/pixelfed/app/Util/ActivityPub/Inbox.php(35): App\\Util\\ActivityPub\\Inbox->handleVerb()
#18 /opt/www/pixelfed/app/Jobs/InboxPipeline/InboxWorker.php(40): App\\Util\\ActivityPub\\Inbox->handle()
#19 [internal function]: App\\Jobs\\InboxPipeline\\InboxWorker->handle()
#20 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#21 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#22 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#23 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#24 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#25 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\InboxPipeline\\InboxWorker))
#26 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\InboxPipeline\\InboxWorker))
#27 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#28 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\InboxPipeline\\InboxWorker), false)
#29 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(83): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\RedisJob), Array)
#30 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(327): Illuminate\\Queue\\Jobs\\Job->fire()
#31 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(277): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#32 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#33 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\\Queue\\Worker->daemon('redis', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#34 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(86): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'default')
#35 /opt/www/pixelfed/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\\Queue\\Console\\WorkCommand->handle()
#36 [internal function]: Laravel\\Horizon\\Console\\WorkCommand->handle()
#37 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#38 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#39 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#40 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#41 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#42 /opt/www/pixelfed/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#43 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#44 /opt/www/pixelfed/vendor/symfony/console/Application.php(901): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#45 /opt/www/pixelfed/vendor/symfony/console/Application.php(262): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#46 /opt/www/pixelfed/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#47 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#48 /opt/www/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#49 /opt/www/pixelfed/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#50 {main}
"}
```

Is the postgresql schema compatible with federation at this time ?

Thanks !

**Comment by asonix** [comment]
Here's the original error that is fixed by increasing the limit on the bio
```
[2019-01-02 21:39:46] production.ERROR: SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(150) (SQL: insert into "profiles" ("domain", "username", "name", "bio", "sharedInbox", "inbox_url", "outbox_url", "remote_url", "public_key", "key_id", "updated_at", "created_at") values (asonix.dog, @asonix@asonix.dog, Arlo (Hyena) uwu, <p>Instance Admin, <a href="https://asonix.dog/tags/furry">#furry</a>,polyam, 23, programmer,Header by <a href="https://asonix.dog/@ruca">@ruca</a>Icon by <a href="https://snouts.online/@demoweasel">@demoweasel</a></p>, https://asonix.dog/inbox, https://asonix.dog/users/asonix/inbox, https://asonix.dog/users/asonix/outbox, https://asonix.dog/users/asonix, -----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwEvEsHqM3twoC2F3KYMQ
9YOialfVQX4StkLvhLUwFv8qpmY7ZSHHl2TWpnzlo5iWS5Pi2vC41HUGYz9XT5G7
4IUOyuIkjTL1FIcPJDcUFCzQjN3QZcHLPJPJVNOOOEiOk8//paOyrqJTq9ikcJDM
J8KTWQgk1leOxUVEN5uaQ+p9IBFbXC76+RqabfEoqLZagVMDSOfeC2uR9xZ1q5Hk
FveRTGs84QLR7FJVvx078nszx4UQGnmP0M+0sOeRJGK17IoJmhaok1XBpP6XFQ45
vYeIRiaFj0Pc9GNISCW70dVXKMhv+K07orQJm6PwP8USyhq4tLkq6tcPbGRqEk3Z
XwIDAQAB
-----END PUBLIC KEY-----
, https://asonix.dog/users/asonix#main-key, 2019-01-02 21:39:46, 2019-01-02 21:39:46) returning "id") {"exception":"[object] (Illuminate\\Database\\QueryException(code: 22001): SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(150) (SQL: insert into \"profiles\" (\"domain\", \"username\", \"name\", \"bio\", \"sharedInbox\", \"inbox_url\", \"outbox_url\", \"remote_url\", \"public_key\", \"key_id\", \"updated_at\", \"created_at\") values (asonix.dog, @asonix@asonix.dog, Arlo (Hyena) uwu, <p>Instance Admin, <a href=\"https://asonix.dog/tags/furry\">#furry</a>,polyam, 23, programmer,Header by <a href=\"https://asonix.dog/@ruca\">@ruca</a>Icon by <a href=\"https://snouts.online/@demoweasel\">@demoweasel</a></p>, https://asonix.dog/inbox, https://asonix.dog/users/asonix/inbox, https://asonix.dog/users/asonix/outbox, https://asonix.dog/users/asonix, -----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwEvEsHqM3twoC2F3KYMQ
9YOialfVQX4StkLvhLUwFv8qpmY7ZSHHl2TWpnzlo5iWS5Pi2vC41HUGYz9XT5G7
4IUOyuIkjTL1FIcPJDcUFCzQjN3QZcHLPJPJVNOOOEiOk8//paOyrqJTq9ikcJDM
J8KTWQgk1leOxUVEN5uaQ+p9IBFbXC76+RqabfEoqLZagVMDSOfeC2uR9xZ1q5Hk
FveRTGs84QLR7FJVvx078nszx4UQGnmP0M+0sOeRJGK17IoJmhaok1XBpP6XFQ45
vYeIRiaFj0Pc9GNISCW70dVXKMhv+K07orQJm6PwP8USyhq4tLkq6tcPbGRqEk3Z
XwIDAQAB
-----END PUBLIC KEY-----
, https://asonix.dog/users/asonix#main-key, 2019-01-02 21:39:46, 2019-01-02 21:39:46) returning \"id\") at /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(150) at /home/pixelfed/live/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119, PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(150) at /home/pixelfed/live/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)
[stacktrace]
#0 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('insert into \"pr...', Array, Object(Closure))
#1 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('insert into \"pr...', Array, Object(Closure))
#2 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Database/Connection.php(304): Illuminate\\Database\\Connection->select('insert into \"pr...', Array, false)
#3 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/PostgresProcessor.php(20): Illuminate\\Database\\Connection->selectFromWriteConnection('insert into \"pr...', Array)
#4 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2615): Illuminate\\Database\\Query\\Processors\\PostgresProcessor->processInsertGetId(Object(Illuminate\\Database\\Query\\Builder), 'insert into \"pr...', Array, 'id')
#5 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1318): Illuminate\\Database\\Query\\Builder->insertGetId(Array, 'id')
#6 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(823): Illuminate\\Database\\Eloquent\\Builder->__call('insertGetId', Array)
#7 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(788): Illuminate\\Database\\Eloquent\\Model->insertAndSetId(Object(Illuminate\\Database\\Eloquent\\Builder), Array)
#8 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(651): Illuminate\\Database\\Eloquent\\Model->performInsert(Object(Illuminate\\Database\\Eloquent\\Builder))
#9 /home/pixelfed/live/app/Util/ActivityPub/Helpers.php(314): Illuminate\\Database\\Eloquent\\Model->save()
#10 /home/pixelfed/live/app/Http/Controllers/FederationController.php(221): App\\Util\\ActivityPub\\Helpers::profileFirstOrNew('https://asonix....')
#11 /home/pixelfed/live/app/Http/Controllers/FederationController.php(185): App\\Http\\Controllers\\FederationController->verifySignature(Object(Illuminate\\Http\\Request), Object(App\\Profile))
#12 [internal function]: App\\Http\\Controllers\\FederationController->userInbox(Object(Illuminate\\Http\\Request), 'asonix')
#13 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#14 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('userInbox', Array)
#15 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\FederationController), 'userInbox')
#16 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#17 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Routing\\Route->run()
#18 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 60, '1')
#24 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Routing/Router.php(684): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#27 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#28 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#29 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#30 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#31 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#32 /home/pixelfed/live/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /home/pixelfed/live/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#39 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#52 /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#53 /home/pixelfed/live/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#54 {main}
"} 
```

**Comment by trwnh** [comment]
If this is still occurring, please post about it in #775 so we can track all the database issues in one place. Thanks!
