### ISSUE TITLE
Thumbnails fail to generate with S3 storage enabled

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#726]
# Problem
When using S3 as the filesystem driver, image thumbnails fail to generate.
Additionally, `AvatarOptimize` tasks in Horizon fail with:
`Intervention\Image\Exception\NotReadableException: Image source not readable in /var/www/pixelfed/vendor/intervention/image/src/Intervention/Image/AbstractDecoder.php:345`
<details>
<summary>Stack trace [ꜱʜᴏᴡ ᴍᴏʀᴇ]</summary>

```
#0 /var/www/pixelfed/vendor/intervention/image/src/Intervention/Image/AbstractDriver.php(64): Intervention\Image\AbstractDecoder->init('/var/www/pixelf...')
#1 /var/www/pixelfed/vendor/intervention/image/src/Intervention/Image/ImageManager.php(52): Intervention\Image\AbstractDriver->init('/var/www/pixelf...')
#2 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Intervention\Image\ImageManager->make('/var/www/pixelf...')
#3 /var/www/pixelfed/app/Jobs/AvatarPipeline/AvatarOptimize.php(44): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
#4 [internal function]: App\Jobs\AvatarPipeline\AvatarOptimize->handle()
#5 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#6 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#7 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#8 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#9 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#10 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\AvatarPipeline\AvatarOptimize))
#11 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\AvatarPipeline\AvatarOptimize))
#12 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\AvatarPipeline\AvatarOptimize), false)
#14 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(83): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#15 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(327): Illuminate\Queue\Jobs\Job->fire()
#16 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(277): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#17 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#18 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\Queue\Worker->daemon('redis', 'default', Object(Illuminate\Queue\WorkerOptions))
#19 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(86): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'default')
#20 /var/www/pixelfed/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\Queue\Console\WorkCommand->handle()
#21 [internal function]: Laravel\Horizon\Console\WorkCommand->handle()
#22 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#23 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#24 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#25 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#26 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#27 /var/www/pixelfed/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#28 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#29 /var/www/pixelfed/vendor/symfony/console/Application.php(901): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /var/www/pixelfed/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /var/www/pixelfed/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /var/www/pixelfed/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 {main}
```
</details>

<details>
<summary>Data [ꜱʜᴏᴡ ᴍᴏʀᴇ]</summary>

```
{
  "profile": {
    "class": "App\\Profile",
    "id": 16,
    "relations": [
      "avatar"
    ],
    "connection": "mysql"
  },
  "current": "/var/www/pixelfed/storage/app/public/avatars/000/000/000/016/avatar.svg",
  "job": null,
  "connection": null,
  "queue": null,
  "chainConnection": null,
  "chainQueue": null,
  "delay": null,
  "chained": []
}
```
</details>

# Reproduction
1. Enable S3 filesystem driver in `.env` on a fresh instance.
2. Upload an image.
![bug report](https://user-images.githubusercontent.com/30352165/50569144-fc55ab00-0d23-11e9-99f7-e93d15db743c.png)
3. Attempt to view thumbnails on the user profile or Discover section.
![no thumbs profile](https://user-images.githubusercontent.com/30352165/50569195-b3eabd00-0d24-11e9-87e7-e29b22ab6a93.png)
![no thumbs discover](https://user-images.githubusercontent.com/30352165/50569199-b816da80-0d24-11e9-895d-f2162038a750.png)

# Configuration
```
FILESYSTEM_DRIVER=s3
AWS_ACCESS_KEY_ID="data expunged"
AWS_SECRET_ACCESS_KEY="too hot for github"
AWS_DEFAULT_REGION="us-east-1"
AWS_BUCKET="monstergallery"
AWS_URL=https://a.monsterpit.gallery
AWS_ENDPOINT=https://s3.wasabisys.com
```

# Notes
- This instance was freshly created with the S3 configuration in place and not migrated from local storage.

**Comment by dansup** [comment]
@multiple-creatures S3 is not supported yet.
