### ISSUE TITLE
Support PostgreSQL or MariaDB

### ISSUE THREAD

**Issue by AMDG2** [pixelfed/pixelfed#775]
It seems you support only MySQL server which is packaged by none of the majors Linux distributions today.

Is it possible to support either PostgreSQL or MariaDB just to allow administrator to easily deploy PixelFed ?

**Comment by ITwrx** [comment]
i use mariadb on everything where mysql is called for. laravel docs still show mysql as supported with no mention of mariadb. i don't know what that's all about, but i use mariadb on all my laravel apps and it's supported on Homestead (laravel dev's own proprietary laravel hosting platform/app), i think. 

IOW, pixelfed looks to be a laravel app so i'm sure mariadb will work fine, though official upstream, and subsequently pixelfed, support would be preferred.

**Comment by Findus23** [comment]
I am using pixelfed with MariaDB 10.3.12 and didn't have any database-related issues (yet).

But I agree that pixelfed should support at least one database that is supported in every major Linux distribution (So probably PostgreSQL 9.6+ and/or MariaDB 10.1+)

**Comment by dansup** [comment]
@AMDG2 Supporting other database drivers is on the roadmap.

**Comment by asonix** [comment]
FWIW I'm running Pixelfed in production on Postgres right now and things mostly seem to work. I needed to run a couple commands to make the DB play nice after migrations were done but otherwise it seems okay

**Comment by Zanonia** [comment]
@asonix 

Postgres instaces are already too buggy for regular use.
The risk is that it will get worse and worse :(

**Comment by asonix** [comment]
well, guess I'll stop hosting when it breaks

**Comment by darix** [comment]
@asonix do you have any documentation about the needed changes/patches for running on postgresql?

**Comment by asonix** [comment]
@darix from #677 there's
```pgsql
ALTER TABLE profiles ALTER COLUMN bio TYPE CHARACTER VARYING;
```
and then to fix the next issue
```pgsql
ALTER TABLE notifications ALTER COLUMN profile_id DROP NOT NULL;
```

**Comment by rhonda** [comment]
I've digged into the issue why MariaDB might be listed as not supported.  From what I can tell it might be related to the support of the JSON Data Type - which got introduced in 10.2.7:

https://mariadb.com/kb/en/library/json-data-type/

I've submitted a merge request to update the README accordingly: https://github.com/pixelfed/pixelfed/pull/804

**Comment by asonix** [comment]
## Upgrade notes for PostgreSQL
I've encountered a couple problems since upgrading to the latest pixelfed on postgres, so here's my notes

### Access Admin Dashboard:
The admin dashboard doesn't load on postgres since a mysql-specific function is used
 - Problem:
```
HINT:  No function matches the given name and argument types. You might need to add explicit type casts. (SQL: select count(*) as count, day(failed_at) as d from \"failed_jobs\" where \"failed_at\" between 2019-01-19 18:03:04 and 2019-02-12 18:03:04 group by \"d\" order by \"d\" asc) at /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 42883): SQLSTATE[42883]: Undefined function: 7 ERROR:  function day(timestamp without time zone) does not exist
        LINE 1: select count(*) as count, day(failed_at) as d from \"failed_j...
```

 - Solution:
    - Create a function for postgres called `day` that does what the mysql `day` function does
```
CREATE OR REPLACE FUNCTION day(in TIMESTAMP WITHOUT TIME ZONE)
    RETURNS INTEGER AS $$
        BEGIN
            RETURN EXTRACT(DAY FROM $1);
        END
    $$ LANGUAGE plpgsql;
```

### Scan Instances:
The admin dashboard can't scan for instances since MySQL handles `groupBy` slightly differently from PostgreSQL
 - Problem:
```
[2019-02-12 18:23:21] production.ERROR: SQLSTATE[42803]: Grouping error: 7 ERROR:  column "profiles.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: select * from "profiles" where "domain" is not null and "pro...
               ^ (SQL: select * from "profiles" where "domain" is not null and "profiles"."deleted_at" is null group by "domain" order by "profiles"."id" asc limit 50 offset 0) {"userId":1,"email":"asonix@asonix.dog","exception":"[object] (Illuminate\\Database\\QueryException(code: 42803): SQLSTATE[42803]: Grouping error: 7 ERROR:  column \"profiles.id\" must appear in the GROUP BY clause or be used in an aggregate function
```

 - Solution:
    - Add `->groupBy('id')` after `->groupBy('domain')` in `app/Http/Admin/AdminInstanceController.php` around line 54

**Comment by asonix** [comment]
Another error just showed up in my logs. Haven't worked this one out, yet.

```
[2019-02-12 18:54:29] production.ERROR: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "relationships" (SQL: select * from "profiles" where "status" is null and "profiles"."id" = relationships and "profiles"."deleted_at" is null limit 1) {"userId":1,"email":"asonix@asonix.dog","exception":"[object] (Illuminate\\Database\\QueryException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"relationships\" (SQL: select * from \"profiles\" where \"status\" is null and \"profiles\".\"id\" = relationships and \"profiles\".\"deleted_at\" is null limit 1) at /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"relationships\" at /home/pixelfed/live/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119, PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"relationships\" at /home/pixelfed/live/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)
```

from
```
#11 /home/pixelfed/live/app/Http/Controllers/PublicApiController.php(358): Illuminate\\Database\\Eloquent\\Builder->findOrFail('relationships')
```

**Comment by dansup** [comment]
I have released a lot of postgres related bug fixes over the past few days. If you notice any more, please report them here!

@asonix All the bugs you reported are fixed in the latest commits, thanks for your help!

**Comment by darix** [comment]
Running pixelfed-0.7.6~git461.c3608ad-lp151.15.1.noarch against postgresql with all migrations run:

````
[2019-02-27 21:48:13] production.ERROR: SQLSTATE[42703]: Undefined column: 7 ERROR:  column "data_length" does not exist
LINE 1: SELECT sum(ROUND(((data_length + index_length)), 0)) AS size...
                           ^ (SQL: SELECT sum(ROUND(((data_length + index_length)), 0)) AS size FROM information_schema.TABLES WHERE table_schema = pixelfed) {"userId":1,"email":"darix@....","exception":"[object] (Illuminate\\Database\\QueryException(code: 42703): SQLSTATE[42703]: Undefined column: 7 ERROR:  column \"data_length\" does not exist
LINE 1: SELECT sum(ROUND(((data_length + index_length)), 0)) AS size...
                           ^ (SQL: SELECT sum(ROUND(((data_length + index_length)), 0)) AS size FROM information_schema.TABLES WHERE table_schema = pixelfed) at /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 42703): SQLSTATE[42703]: Undefined column: 7 ERROR:  column \"data_length\" does not exist
LINE 1: SELECT sum(ROUND(((data_length + index_length)), 0)) AS size...
                           ^ at /srv/www/vhosts/pixelfed/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119, PDOException(code: 42703): SQLSTATE[42703]: Undefined column: 7 ERROR:  column \"data_length\" does not exist
LINE 1: SELECT sum(ROUND(((data_length + index_length)), 0)) AS size...
                           ^ at /srv/www/vhosts/pixelfed/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)
[stacktrace]
#0 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('SELECT sum(ROUN...', Array, Object(Closure))
#1 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('SELECT sum(ROUN...', Array, Object(Closure))
#2 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(327): Illuminate\\Database\\Connection->select('SELECT sum(ROUN...', Array)
#3 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Illuminate\\Database\\DatabaseManager->__call('select', Array)
#4 /srv/www/vhosts/pixelfed/app/Http/Controllers/Admin/AdminSettingsController.php(43): Illuminate\\Support\\Facades\\Facade::__callStatic('select', Array)
#5 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(340): App\\Http\\Controllers\\AdminController->App\\Http\\Controllers\\Admin\\{closure}()
#6 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(323): Illuminate\\Cache\\Repository->remember('admin:settings:...', Object(Illuminate\\Support\\Carbon), Object(Closure))
#7 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Illuminate\\Cache\\CacheManager->__call('remember', Array)
#8 /srv/www/vhosts/pixelfed/app/Http/Controllers/Admin/AdminSettingsController.php(44): Illuminate\\Support\\Facades\\Facade::__callStatic('remember', Array)
#9 [internal function]: App\\Http\\Controllers\\AdminController->settingsStorage(Object(Illuminate\\Http\\Request))
#10 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#11 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('settingsStorage', Array)
#12 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\AdminController), 'settingsStorage')
#13 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#14 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Routing\\Route->run()
#15 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#16 /srv/www/vhosts/pixelfed/app/Http/Middleware/TwoFactorAuth.php(33): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#17 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\TwoFactorAuth->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /srv/www/vhosts/pixelfed/app/Http/Middleware/Admin.php(24): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\Admin->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#41 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Router.php(684): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#42 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#43 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#44 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#45 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#46 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#47 /srv/www/vhosts/pixelfed/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#54 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#57 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#60 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#63 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#64 /srv/www/vhosts/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#65 /srv/www/vhosts/pixelfed/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#66 {main}
"} 
```

**Comment by dansup** [comment]
@darix Fixed in latest commits.

I'm still using Postgres locally and haven't come across any other bugs yet.

**Comment by darix** [comment]
another issue with postgresql:
```
artisan user:show testing
In Connection.php line 664:
  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "testing" (SQL: select * from "users" where ("username" = testing or "id" = testing) and "users"."deleted_at" is null
  limit 1)
In PDOStatement.php line 119:
  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "testing"
In PDOStatement.php line 117:
  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "testing"
```

on mysql flavors it would cast the string to a number and tries to compare that. for PG this doesnt work. but maybe the support for the old DB schema can be removed after the migration?

**Comment by shleeable** [comment]
I've enabled pgsql on the docker and working to assist but I'm also having lots of problems.

I cannot delete anything. I cannot delete posts, comments, users as admin.

**Comment by AMDG2** [comment]
@Shleeble maybe you should open a dedicated issue with logs and more information.

**Comment by shleeable** [comment]
FYI: Those problems were because horizon was not running... resolved :)
