### ISSUE TITLE
 Uncaught InvalidArgumentException: Route [remotefollow] not defined

### ISSUE THREAD

**Issue by MrPetovan** [pixelfed/pixelfed#937]
Just updated to e4a6390e8fedfe8bbb2fc81ada80ab8ceb5abf53

Login/Password reset work, however, when I login successfully, here's the 500 error I get on `/home`:
```
PHP Fatal error:  Uncaught InvalidArgumentException: Route [remotefollow] not defined. in vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:388
Stack trace:
#0 vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(778): Illuminate\\Routing\\UrlGenerator->route('remotefollow', Array, true)
#1 storage/framework/views/a53302cdd370a21be8abe60919b4b3eceb7529ad.php(62): route('remotefollow')
#2 vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): include('/home/pixelfed/...')
#3 vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\\View\\Engines\\PhpEngine->evaluatePath('/home/pixelfed/...', Array)
#4 vendor/laravel/framework/src/Illuminate/View/View.php(142): Illuminate\\View\\Engines\\CompilerEngine->get('/home/pixelfed/...', Array)
#5 in vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 388
```

Sorry for the incomplete stack trace.

**Comment by dansup** [comment]
@MrPetovan Please run ```php artisan route:cache```, the remotefollow route was removed awhile ago iirc.

**Comment by MrPetovan** [comment]
```
$ php artisan route:cache
Route cache cleared!
Routes cached successfully!
```

Still getting the same error browsing `/`.

**Comment by MrPetovan** [comment]
Nevermind, I'm wrongly trying to start a production instance, at this point this is just unnecessary noise for you.
